### ISSUE TITLE
Prometheus not starting

### ISSUE THREAD

**Issue by gwenvador** [eth-educators/eth-docker#1006]
I have upgraded to latest eth-docker version and prometheus is not restarting. I have the following error:

> Error loading config (--config.file=/etc/prometheus/prometheus.yml)" file=/etc/prometheus/prometheus.yml err="parsing YAML file /etc/prometheus/prometheus.yml: found multiple scrape configs with job name \"nodes\""

**Comment by gwenvador** [comment]
for information I am using lighthouse + nethermind. Nethermind is logging (I guess because prometheus not starting):

> Could not reach PushGatewayUrl, Please make sure you have set the correct endpoint in the configurations. System.Net.Http.HttpRequestException: Cannot assign requested address (localhost:9091)

**Comment by gwenvador** [comment]
It looks like the /etc/prometheus/prometheus.yml in the docker keeps adding configurations. I have 80 job_name:nethermind entries.

**Comment by yorickdowne** [comment]
Oh grief I think I know why. Thanks. I'll get that fixed.

**Comment by yorickdowne** [comment]
Please try an `./ethd update` followed by `./ethd up`, it should fix both issues. Thanks for the report!
