### ISSUE TITLE
v2.1.2 Grafana stopped working

### ISSUE THREAD

**Issue by jakrypto** [eth-educators/eth-docker#1014]
<img width="1430" alt="Screenshot 2022-10-04 at 22 38 38" src="https://user-images.githubusercontent.com/78829592/193910565-a840b195-771d-408b-a757-4c964c11facf.png">

Grafana stopped working for me with the new update, could be an issue with prometheus. Any ideas?

**Comment by yorickdowne** [comment]
Can you see whether Prometheus is running correctly? 

There have been quite a few changes recently to Prometheus. Knowing your full `COMPOSE_FILE` may help. I've just tried it on a fresh install with Teku and Besu and I am getting metrics.

Working through this on ethstaker Discord will be faster than a Github issue

**Comment by yorickdowne** [comment]
We went through this on Discord. Prometheus is collecting metrics and Grafana sees them.
