### ISSUE TITLE
./ethd update fails as ext-network.yml has local changes when using rocketpool

### ISSUE THREAD

**Issue by stefanlsd** [eth-educators/eth-docker#1015]
When using Rocketpool only the ext-network.yml file is modified and future "./ethd update"'s fail as this file has local changes.

```
~/eth-docker$ ./ethd update
Updating 081a46c..ce576d1
error: Your local changes to the following files would be overwritten by merge:
        ext-network.yml
Please commit your changes or stash them before you merge.
Aborting
Building validator
```

**Comment by yorickdowne** [comment]
Yep. You have choices. You can commit this, and get a merge prompt in future.

You can `git restore ext-network.yml`, run an `./ethd update`, then when everything is up, edit `ext-network.yml` again and check with `git status`. The changes should now be hidden from git.

Only run `./ethd up` once this has been resolved and you're on a current version. There may be a switch to a different branch if you're currently on `merge-getready` and not `main`, so you want to make sure you come to the current release before recreating the change.
