### ISSUE TITLE
Cannot connect to RPC

### ISSUE THREAD

**Issue by Sofianel5** [eth-educators/eth-docker#1023]
# Background
I'm trying to run a RPC node (consensus & execution, but not a validator/staker) on AWS that I can use instead of infura. I've tried with multiple client combinations (teku/besu, teku/erigon, and finally lighthouse/geth). None of them launched with eth-docker create an HTTP RPC port I can connect to.
# To reproduce:
### Set up EC2 Instance
m5.2xlarge Ubuntu 22.04
Open tcp/udp for ports 9000,30303,8545,8546
### Fresh install of eth-docker
>$  git clone https://github.com/eth-educators/eth-docker.git && cd eth-docker
>$ ./ethd install
This will attempt to install docker and make your user part of the docker group. Do you wish to continue? (no/yes) yes
>$ ./ethd config
Your configuration file template is: default.env
You chose to run on Ethereum mainnet
Your deployment choice is: rpc
Your consensus client file is: lighthouse-cl-only.yml
Your execution client file is: geth.yml
>$ ./ethd up
[+] Running 6/6
 ⠿ Network eth-docker_default            Created                                                                                                                                                      0.0s
 ⠿ Volume "eth-docker_lhconsensus-data"  Created                                                                                                                                                      0.0s
 ⠿ Volume "eth-docker_jwtsecret"         Created                                                                                                                                                      0.0s
 ⠿ Volume "eth-docker_geth-eth1-data"    Created                                                                                                                                                      0.0s
 ⠿ Container eth-docker-execution-1      Started                                                                                                                                                      0.6s
 ⠿ Container eth-docker-consensus-1      Started 
>$ ./ethd logs -f
eth-docker-execution-1  | INFO [10-16|02:49:28.756] HTTP server started                      endpoint=[::]:8545 auth=false prefix= cors=* vhosts=*
eth-docker-execution-1  | INFO [10-16|02:49:28.757] WebSocket enabled                        url=ws://[::]:8546
eth-docker-execution-1  | INFO [10-16|02:49:28.757] WebSocket enabled                        url=ws://[::]:8551
eth-docker-execution-1  | INFO [10-16|02:49:28.757] HTTP server started                      endpoint=[::]:8551 auth=true  prefix= cors=localhost vhosts=*

## Testing RPC
>$ docker ps
CONTAINER ID   IMAGE              COMMAND                  CREATED          STATUS          PORTS                                                               NAMES
bee3b0727ee3   lighthouse:local   "docker-entrypoint.s…"   20 minutes ago   Up 20 minutes   0.0.0.0:9000->9000/tcp, 0.0.0.0:9000->9000/udp                      eth-docker-consensus-1
fefc69a3c543   geth:local         "docker-entrypoint.s…"   20 minutes ago   Up 20 minutes   8545-8546/tcp, 0.0.0.0:30303->30303/tcp, 0.0.0.0:30303->30303/udp   eth-docker-execution-1
>$ sudo netstat -tulpn | grep LISTEN
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      441/systemd-resolve 
tcp        0      0 0.0.0.0:30303           0.0.0.0:*               LISTEN      4848/docker-proxy   
tcp        0      0 0.0.0.0:9000            0.0.0.0:*               LISTEN      4880/docker-proxy   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      813/sshd: /usr/sbin 
tcp6       0      0 :::22                   :::*                    LISTEN      813/sshd: /usr/sbin 
>$ curl 0.0.0.0:8545
curl: (7) Failed to connect to 0.0.0.0 port 8545 after 0 ms: Connection refused
>$ curl 0.0.0.0:8546
curl: (7) Failed to connect to 0.0.0.0 port 8546 after 0 ms: Connection refused
>$ curl 0.0.0.0:5052
curl: (7) Failed to connect to 0.0.0.0 port 5052 after 0 ms: Connection refused

**Comment by yorickdowne** [comment]
This is likely because you did not expose the port. `ec-shared.yml` would expose RPC ports, and also take a look at https://eth-docker.net/docs/Usage/ReverseProxy if you want to use `ec-traefik.yml` instead and expose this securely over 443. These are added to `COMPOSE_FILE` in `.env`

https://eth-docker.net/docs/Usage/ClientSetup has a list of the most commonly used yml files

**Comment by Sofianel5** [comment]
Thanks for the response! 

I got the RPC to work (but not over SSL) by adding `:el-shared.yml:el-traefik.yml` to `COMPOSE_FILE` in my `.env` and adding custom values to `DOMAIN` and `ACME_EMAIL`. I see in https://eth-docker.net/docs/Usage/ReverseProxy that I need to add`ec-traefik.yml` as well, but I can't find that file in this repository. Has it been renamed, to `ee-traefik.yml` for example?

**Comment by yorickdowne** [comment]
el-shared.yml and el-traefik.yml are two different ways of doing this. el-shared host maps the port directly; el-traefik also requires traefik-cf or traefik-aws and then it'll be reachable via 443. ec-traefik has been renamed to el-traefik. I'll fix the docs, thanks!

**Comment by Sofianel5** [comment]
Has this been tested recently? I'm using `nimbus-cl-only.yml:erigon.yml:el-shared.yml:el-traefik.yml:ee-traefik.yml:traefik-aws.yml` on one machine and `lighthouse-cl-only.yml:geth.yml:el-shared.yml:el-traefik.yml:ee-traefik.yml:traefik-aws.yml` on another and neither implements TLS properly. Attempting to connect to either (https://DOMAIN or via my CNAME https://el.DOMAIN) via curl yields 
```
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* error:1404B42E:SSL routines:ST_CONNECT:tlsv1 alert protocol version
* Closing connection 0
curl: (35) error:1404B42E:SSL routines:ST_CONNECT:tlsv1 alert protocol version
```
Inspecting `docker volume ls` shows a volume called `eth-docker_certs` which contains `/var/lib/docker/volumes/eth-docker_certs/_data/acme.json`, what appears to be a valid ACME JSON file with certificates for el-lb, cl-lb, ee, cl, elws, el, elws-lb subdomains. Additionally, `./ethd logs traefik` yields only
`eth-docker-traefik-1  | time="2022-10-19T09:02:37Z" level=info msg="Configuration loaded from flags."`
and my route 53 console showed that TXT records were created for _ACME_CHALLENGE.subdomain for the above subdomains of DOMAIN. Not sure what I could be doing wrong

**Comment by yorickdowne** [comment]
I am using this in production, though with CloudFlare. 

So first you don't want `el-shared.yml` or `ee-traefik.yml`, that's a direct-mapped RPC port and traefik engine API (!) port respectively. Not useful or desired.

With AWS you will be creating your A records and CNAME records manually, see the docs for that.

For traefik you can turn on debug, see the `traefik-aws.yml`, and see how it behaves. Ditto for turning on connection logging if you like, it can be useful during troubleshooting.
