### ISSUE TITLE
Best way to connect to JSON RPC? (To trigger pruning in Nethermind)

### ISSUE THREAD

**Issue by thomkeh** [eth-educators/eth-docker#1037]
I wanted to manually trigger pruning on my Nethermind execution client. [The documentation says to use this](https://docs.nethermind.io/nethermind/ethereum-client/json-rpc/admin#admin_prune):

```
curl --data '{"method":"admin_prune","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
```
However, this fails because port 8545 from the Nethermind container isn't exposed on localhost.

My next idea was to use `docker exec`:
```
docker exec <nethermind container ID> curl --data [...] localhost:8545
```
but the Nethermind docker doesn't have `curl` installed...

However, the Teku docker does have `curl`, so in the end I was able to use
```
docker exec <teku container ID> curl --data [...] execution:8545
```
(after I added "Admin" to `--JsonRpc.EnabledModules` in `nethermind.yml`)

So, this worked, but is there a better way?

**Comment by yorickdowne** [comment]
There is indeed a better way. You can exec into the Nethermind container with `bash` as `root`, install `curl`, and do it locally.

Nethermind pruning is a good question. At some point it needs to become a feature of eth-docker ... hence the issue for it. Unless I can avoid it long enough for Nethermind to change their state storage ways. But that's looking increasingly unlikely.

**Comment by yorickdowne** [comment]
2.2.0 now supports `./ethd nethermind-prune`. Thanks for giving me a reason to implement this!

**Comment by thomkeh** [comment]
> Thanks for giving me a reason to implement this!

My pleasure 😄
