### ISSUE TITLE
Can a flag be added to ethd restart command?

### ISSUE THREAD

**Issue by Mercury196** [eth-educators/eth-docker#1078]
Recommend a flag option to ethd restart command for a single override of .env parameter. Currently, I edit the .env file before and after I run ethd restart to set doppelganger=false for one instance. I keep .env set to doppelganger=true but for an intentional restart, I will disable doppelganger one time.

**Comment by yorickdowne** [comment]
Doppelganger really is only meant to be used for moving keys. Restarts don't require it, as you are in the same instance of the validator client and the validator client has a slashing protection DB inside persistent storage, its docker volume.

Unless you have reason to believe your keys may become active in another instance of the validator client, with different storage, there's no need to use doppelganger.

**Comment by Mercury196** [comment]
Hi Yorick. Thank you for the response. I agree doppelganger is 99.999...%
not needed for restart. I keep it enabled for any uncommanded restart to
handle the very rare (but possible) bug, hardware failure, db corruption,
power outtage combination where having it enabled "might" help mitigate a
problem. Risk/reward for me says to keep it enabled. Maybe it's just peace
of mind. Anyhow, I edit .env before and after every update and restart for
this reason.

Cheers and happy holidays!!
