### ISSUE TITLE
building nethermind from source fails when checking out submodules

### ISSUE THREAD

**Issue by nu404040** [eth-educators/eth-docker#1086]
Step 6/22 : RUN bash -c "git clone https://github.com/NethermindEth/nethermind && cd nethermind && git config advice.detachedHead false && git fetch --all --tags && git checkout ${
BUILD_TARGET} && git submodule update --init src/Dirichlet src/int256 src/rocksdb-sharp src/Math.Gmp.Native &&     dotnet publish src/Nethermind/Nethermind.Runner -c release -o out
"
 ---> Running in b267acd89bc2
Cloning into 'nethermind'...                                                                                                                                                        Updating files: 100% (4918/4918), done.                                                                                                                                             Fetching origin
HEAD is now at 4fe81c6bc Bump version
error: pathspec 'src/Dirichlet' did not match any file(s) known to git
error: pathspec 'src/int256' did not match any file(s) known to git
error: pathspec 'src/rocksdb-sharp' did not match any file(s) known to git
error: pathspec 'src/Math.Gmp.Native' did not match any file(s) known to git

**Comment by yorickdowne** [comment]
Thanks for the PR!
