### ISSUE TITLE
How to access Geth RPC api locally outside docker

### ISSUE THREAD

**Issue by or2008** [eth-educators/eth-docker#1094]
after successful installtion and full sync I am trying to access geth http api on the local machine, with curl like so:

```
curl -X POST --data '{"jsonrpc":"2.0","method":"net_version","params":[],"id":67}' http://127.0.0.1:8545
```

but getting the following error:
`
Failed to connect to 127.0.0.1 port 8545 after 0 ms: Connection refused
`

everything runs without errors so I am not sure what's wrong. 
this is the `docker ps` output:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/3414979/205946715-2c916b04-f0b4-4101-a146-ca4c3ec7880f.png">

full docker command:
```
docker-entrypoint.sh geth --http --http.addr 0.0.0.0 --http.vhosts=* --http.corsdomain=* --http.api web3,eth,net --datadir /var/lib/goethereum --port 30303 --http.port 8545 --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.api web3,eth,net --mainnet --metrics --metrics.expensive --pprof --pprof.addr 0.0.0.0 --authrpc.jwtsecret /var/lib/goethereum/ee-secret/jwtsecret --authrpc.addr 0.0.0.0 --authrpc.port 8551 --authrpc.vhosts=* --maxpeers 50
``` 

any idea how can I fix that?

**Comment by yorickdowne** [comment]
Use `el-shared.yml` in your `COMPOSE_FILE` to expose the API port
