### ISSUE TITLE
Teku Invalid SNI 

### ISSUE THREAD

**Issue by alepacheco** [eth-educators/eth-docker#1101]
With the latest version of teku validator API returns an error for Invalid SNI. 

See: https://github.com/ConsenSys/teku/issues/6564

**Comment by yorickdowne** [comment]
Thanks for the report! Let me see what's needed.

**Comment by dsimog01** [comment]
Hey @yorickdowne , I am a developer from DAppNode. We are facing some issues related to this issue... Would you be so kind to tell me where I can contact you (discord, Telegram) if you were willing to give me a hand? Thanks in advance :)

**Comment by yorickdowne** [comment]
Discord is easiest @dsimog01 - please find me in ethstaker Discord, https://discord.io/ethstaker
