### ISSUE TITLE
Feature request: support remote signing

### ISSUE THREAD

**Issue by filoozom** [eth-educators/eth-docker#1103]
It would be lovely if `eth-docker` could support remote signing, through [Web3Signer](https://docs.web3signer.consensys.net/en/latest/) for example.

This could make it more secure (by having multiple options for key storage) and could make it possible to replace the validator client very easily if well implemented, as demonstrated by DAppNode.

**Comment by yorickdowne** [comment]
I've thought on this on and off, and I haven't yet figured out a way to support web3signer that is easy, flexible, and doesn't inconvenience existing users. Suggestions welcome.

Most users will use the same validator client that comes with their consensus layer client. Replacing it is reasonably convenient now with they keymanager API options: Delete keys, which exports the slashing protection DB; switch client; reimport keys with their attendant slashing protection DB.

**Comment by alepacheco** [comment]
Can we make the ethd script check for keys imported in the default client validator and if it finds any export them and import them into web3signer?

**Comment by yorickdowne** [comment]
No, that's not an option technically or design-wise. Technically keymanager API can delete but not export keys. Design-wise I don't want to force people into a specific client.

The main challenge is to avoid a proliferation of yml files. web3signer would have its own key manager API, which means the code that calls it needs to special-case for the eventuality that web3signer exists. The rest can maybe be handled with `VC_EXTRAS` and a `web3signer.yml`.

**Comment by yorickdowne** [comment]
I have some ideas on how to enable this as an advanced feature. I'd like to get it in before the security audit starts.

**Comment by yorickdowne** [comment]
There's a web3signer.yml now. You'd need to see how an individual VC interacts with it, likely via `VC_EXTRAS` in `.env`. Goerli only please!!

Web3signer cautions that their key manager API is early access and still in development: https://docs.web3signer.consensys.net/HowTo/Use-Signing-Keys#manage-keys

Key import works, fee recipient and gas limit are not implemented. I haven't tested key deletion. It also doesn't use a token, unlike all other implementations. Early days indeed.

I'll leave this open as a tracking issue for web3signer integration and their keymanager support. It doesn't feel like it's prime-time ready tbh, mainly because of that keymanager early access status.

**Comment by yorickdowne** [comment]
https://ethereum.github.io/keymanager-APIs/#/Remote%20Key%20Manager/importRemoteKeys is how this would need to be done.

One way to potentially handle this:
- `WEB3SIGNER=true` in `.env`
- `./ethd keys import` checks for local keys if that's set, if so aborts with a warning message
- If no local keys, `import` imports keys into web3signer and pubkey and URL into VC as "remote"
- Gas limit and fee recipient should work as-is

**Comment by yorickdowne** [comment]
This has now been implemented, and tested so far with Lighthouse. Edit `.env` and set `WEB3SIGNER=true`

Please test this on Goerli first, and be extremely careful. Moving keys from the VC to web3signer requires the same care to avoid slashing as moving keys between VCs.

**Comment by yorickdowne** [comment]
Yes I plan to document this after further testing.

It is not ready for mainnet: I have only tested that it works with Lighthouse. This needs to be tested with all clients. Also, I need to add a reregister command so switching clients doesn’t require using then keystore-m again. That’s scary UX.
