### ISSUE TITLE
Teku behind nat options

### ISSUE THREAD

**Issue by alepacheco** [eth-educators/eth-docker#1107]
Teku has the option --p2p-advertised-ip and --p2p-nat-method which could be used when behind a NAT. 

More info: https://docs.teku.consensys.net/en/latest/HowTo/Find-and-Connect/Specifying-NAT/

I wonder if this could be helpful to home validators and we could add a env variable.

**Comment by yorickdowne** [comment]
You can always add this with `CL_EXTRAS`. Teku will however detect NAT automatically and set ENR accordingly.
