### ISSUE TITLE
Support prune docker images in non-standard location

### ISSUE THREAD

**Issue by mLewisLogic** [eth-educators/eth-docker#1112]
Currently, the docker volume location is hardcoded for the disk space check in the pruning function: https://github.com/eth-educators/eth-docker/blob/468c4fe98cdf3c7a3cad0959c79b4570029e6573/ethd#L679-L685

It could be dynamically detected using something like the following:

```sh
export GETH_VOLUME_MOUNTPOINT=`docker inspect eth-docker_geth-eth1-data | jq --raw-output '.[0].Mountpoint'`
```

In my case that gets me `/data/docker/volumes/eth-docker_geth-eth1-data/_data`, which works great with `df`.

**Comment by yorickdowne** [comment]
That's a good point. Let me take a look at it.

**Comment by yorickdowne** [comment]
This should now work and parses daemon.json for the docker data-root. Give it a whirl!
