### ISSUE TITLE
perm issue on `docker-entrypoint.sh`

### ISSUE THREAD

**Issue by mLewisLogic** [eth-educators/eth-docker#1117]
Ran a `./ethd update` and now containers are failing to start.
Previous update was about a week ago, so perhaps something in the interim? I don't believe anything has changed with regards to my host users or groups.

```
/data/code/eth-docker > ./ethd up
[+] Running 0/2
 ⠿ Container eth-docker-execution-1  Starting                                                                                  1.1s
 ⠿ Container eth-docker-consensus-1  Starting                                                                                  1.1s
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec /usr/local/bin/docker-entrypoint.sh: permission denied: unknown
```

Any thoughts on the issue or how to debug more info out of it?
`COMPOSE_FILE=prysm-cl-only.yml:geth.yml:el-shared.yml`

**Comment by yorickdowne** [comment]
Oh boy. I can't reproduce, and looking at the recent changes I've made, I don't immediately see what would have caused this.

Let's start by forcing a build. `./ethd cmd build --pull --no-cache consensus` and then `./ethd up`. If that doesn't do it, please check the permissions with a  `docker run -it --rm --entrypoint bash prysm-consensus:local` and do `ls -lh /usr/local/bin/`

In my case this shows
```
prysmconsensus@3cb73b7212bb:/$ ls -lh /usr/local/bin/
total 60M
-r-xr-xr-x 1 root root 104M Jan  1  1970 beacon-chain
-rwxrwxr-x 1 root root 2.6K Nov 21 20:52 docker-entrypoint.sh
```

As you can see the files are readable and executable by "everyone", which allows the non-root user prysm starts with to use them.

**Comment by yorickdowne** [comment]
I had one report that this could happen with rootless docker, but never got to the bottom of it.

**Comment by yorickdowne** [comment]
For real-time troubleshooting, discord.io/ethstaker please. If this is related to rootless docker, there may be a chance here to find root (badum bish) cause and fix it once and for all.

**Comment by yorickdowne** [comment]
Probably not related to rootless docker. This is what I get when using rootless
```
ubuntu@eth-testing-ovh2:~$ docker exec -it geth-test-consensus-1 bash
prysmconsensus@855b475d601f:/$ ls -lh /usr/local/bin/
total 104M
-r-xr-xr-x 1 root root 104M Jan  1  1970 beacon-chain
-rwxrwxr-x 1 root root 2.6K Dec  6 16:14 docker-entrypoint.sh
```

**Comment by mLewisLogic** [comment]
I think I figured it out.
Due to the way I was syncing files, on my remote, all files had only user permissions, no group/all. So the `docker-entrypoint.sh` file was getting synced with only access permissions for a user that only existed on the host.

Adding a chown after the copy fixed the issue for me. I'd guess it would likely benefit others and I don't think it would do any harm to include in the Dockerfiles.

```docker
COPY ./docker-entrypoint.sh /usr/local/bin/
RUN chown -R ${USER}:${USER} /usr/local/bin/docker-entrypoint.sh
```

**Comment by mLewisLogic** [comment]
Thanks for the debug commands. Helped tremendously.

**Comment by yorickdowne** [comment]
> Due to the way I was syncing files

So not straight from git, without modifications?

I agree a chown or chmod can be done. I'm not doing it right now because it seemed unnecessary as long as the user didn't make manual modifications to the source file permissions.

Understanding how you deployed this would be helpful.

Side effect - there is now a `grafana-rootless.yml` to support rootless mode :)

**Comment by mLewisLogic** [comment]
Ya, I could see this as a “won’t do”, but just noting that git doesn’t actually store any user/group permissions. Just the executable bit. So there’s no way that the git repo itself guarantees against this issue.

Deployed on Ubuntu using apt. Added my user to the docker group. Git clone from the repo and run ‘./ethd’.

**Comment by yorickdowne** [comment]
Yeah I'm adding it. Will take a bit of testing. It touches every build file and I don't want to break a client.
