### ISSUE TITLE
[Improvement] Remote Signer option

### ISSUE THREAD

**Issue by alepacheco** [eth-educators/eth-docker#1124]
I want to propose having a setup flow to use eth-docker with a remote signer. 
This could also be a default option with a container remote signer.
This will help with changing the CC on the fly, keeping the keys segregated and giving more options to users on how to use eth-docker. 
It will also allows users to setup external signers with the script

**Comment by yorickdowne** [comment]
Duplicate of #1103 . Discuss in there please. I am open to ideas on how to implement this without disrupting existing users.
