### ISSUE TITLE
Persist Custom grafana dashboards

### ISSUE THREAD

**Issue by alepacheco** [eth-educators/eth-docker#1143]
I've had my Grafana dashboards get removed after doing an ethd update/up

Can we make sure they are not deleted?

**Comment by yorickdowne** [comment]
That ... shouldn't happen. Grafana has a volume. Was this changes to prepopulated dashboards, or new dashboards brought in?

Please give me steps to reproduce.

**Comment by alepacheco** [comment]
@yorickdowne I don't have clear steps as this happened a few days ago. This was a newly created dashboard and I had deleted some of the provisioned dashboard too.
I think this could be related to the scripts that adds the provisioned dashboards on startup.

**Comment by yorickdowne** [comment]
As expected, I cannot reproduce this. I started a fresh instance and added `1860`, "Node Exporter Full", by its ID. Then did an `./ethd restart`. The dashboard continues to be available.

If you imported a dashboard and it has the same UID as a provisioned one then yes. it'd be overwritten. Is that maybe what happened? Is it possible a provisioned dashboard was deleted, then imported again with the same UID but different contents - and then got overwritten on restart with the provisioned dashboard again?
