### ISSUE TITLE
syntax error near unexpected token

### ISSUE THREAD

**Issue by hiromaily** [eth-educators/eth-docker#1147]
syntax error near unexpected token error happened just fater running `./ethd install`
```
❯ ./ethd install
./ethd: line 1608: syntax error near unexpected token `&'
./ethd: line 1608: `            ;;&
```
I'm trying on MacOS 12.6

**Comment by yorickdowne** [comment]
Please see instructions for macOS at https://eth-docker.net/Usage/Prerequisites#macos-prerequisites

A `brew install bash` followed by logout/login should fix it. macOS ships with bash 3.x, and current `ethd` requires features that were added later. The brew bash is 5.x
