### ISSUE TITLE
ethereum-metrics-exporter is linux/amd only

### ISSUE THREAD

**Issue by nikwest** [eth-educators/eth-docker#1151]
I'm trying to use eth-docker on Apple M1 platform, but the ethereum-metrics-exporter image is linux/amd only. Would be nice to have a multiplatform image.

**Comment by yorickdowne** [comment]
I agree! Please open an issue at https://github.com/ethpandaops/ethereum-metrics-exporter and encourage them to publish a multiarch docker image. eth-docker can then use it.
