### ISSUE TITLE
Error on ./ethd 

### ISSUE THREAD

**Issue by bunbuntigery** [eth-educators/eth-docker#1154]
Just starting playing with eth-docker.  It looks great!  When I follow the official setup steps, I get the following error:

>> ./ethd. (or ./ethd install etc)

./ethd: line 1633: syntax error near unexpected token `&'
./ethd: line 1633: `            ;;&'

Guessing this is just a bash configuration problem but wondering if you've seen it.

**Comment by nflaig** [comment]
Seems related to #1147

**Comment by bunbuntigery** [comment]
Thank you!  Yes.
This got me past that particular error, now I need to install whiptail or
newt ....
