### ISSUE TITLE
Grafana eth-docker dashboard

### ISSUE THREAD

**Issue by gwenvador** [eth-educators/eth-docker#1155]
I recently found this dashboard for grafana : https://grafana.com/grafana/dashboards/17846-homestaking-dashboard/
I am not the author but it seems pretty adapted for eth-docker. I could be worth integrating with current dashboards.

**Comment by yorickdowne** [comment]
Nice one! I can certainly add this

**Comment by yorickdowne** [comment]
Closed by #1160
