### ISSUE TITLE
ethereum-metrics-exporter seems broken

### ISSUE THREAD

**Issue by nflaig** [eth-educators/eth-docker#1164]
Pulled latest changes from main branch, commit `dc9365b8ed7cea08d2f7ea10546c0254b1e65656`

The `ethereum-metrics-exporter` does not start, there seems to an issue with an missing folder/file

error logs

```
/usr/local/bin/docker-entrypoint.sh: line 11: /ethereum-metrics-exporter: No such file or directory
/usr/local/bin/docker-entrypoint.sh: line 11: /ethereum-metrics-exporter: No such file or directory
/usr/local/bin/docker-entrypoint.sh: line 11: /ethereum-metrics-exporter: No such file or directory
/usr/local/bin/docker-entrypoint.sh: line 11: /ethereum-metrics-exporter: No such file or directory
/usr/local/bin/docker-entrypoint.sh: line 11: /ethereum-metrics-exporter: No such file or directory
/usr/local/bin/docker-entrypoint.sh: line 11: /ethereum-metrics-exporter: No such file or directory
```

Ubuntu **22.04.1 LTS**
Docker version **20.10.23**, build 7155243
Docker Compose version **v2.15.1**

**Comment by yorickdowne** [comment]
Try an `./ethd update`. There was a change to the image and it now pulls `debian-latest` instead of `latest`

When you pull and don't use the update command, images are not built. This can cause issues.

**Comment by nflaig** [comment]
I used `./ethd update` to do the update and even removed the image to give it another try.

On further investigation I think the problem is that we are calling `/ethereum-metrics-exporter`

https://github.com/eth-educators/eth-docker/blob/3231823bfaae0fc0c1edf9d4b9d3465280da4055/grafana.yml#L39-L42

Both the `latest` and `debian-latest` are broken at the moment, see image layers

[**debian-latest**](https://hub.docker.com/layers/samcm/ethereum-metrics-exporter/debian-latest/images/sha256-b575352e5a3dc1fe0201356ffd8773073051a2ba3e24bd1d5cbfed0c069b523e?context=explore) (2 days old)

![image](https://user-images.githubusercontent.com/38436224/217622211-ca577218-1628-4ccb-852a-1d69c3834a07.png)


[**0.19.0**](https://hub.docker.com/layers/samcm/ethereum-metrics-exporter/0.19.0/images/sha256-6ae8f316d10b7e34be5ee13b153fbe456a53c1b7f8bdf0a93a99c460e4ea064e?context=explore) (2 months old)

![image](https://user-images.githubusercontent.com/38436224/217622037-bb9553cc-6d9b-44d0-b4cc-cf3a7588af59.png)

**Comment by nflaig** [comment]
issue can be solved by updating `grafana.yml`

![image](https://user-images.githubusercontent.com/38436224/217622841-b993a1ba-de35-4e49-b98f-bc7a79a3905c.png)

**Comment by yorickdowne** [comment]
Fun and games! OK thank

**Comment by caevv** [comment]
This is now failing for me, they changed it back on `debian-latest`, fixed by reverting it back:

```diff
diff --git a/grafana.yml b/grafana.yml
index cdc4448..b205d64 100644
--- a/grafana.yml
+++ b/grafana.yml
@@ -38,7 +38,7 @@ services:
       - CLIENT=${COMPOSE_FILE}
     entrypoint:
       - docker-entrypoint.sh
-      - /exporter
+      - /ethereum-metrics-exporter
     <<: *logging
```

https://hub.docker.com/layers/samcm/ethereum-metrics-exporter/debian-latest/images/sha256-fcc19a9fedb279dd4cacc22f5fa3cd8a46da0ecd937ac1d23826efd83854379e?context=explore

**Comment by nflaig** [comment]
yeah, its annoying...fix is on the way https://github.com/eth-educators/eth-docker/pull/1199, or you might just pin the ethereum metrics exporter version as suggested in this PR https://github.com/eth-educators/eth-docker/pull/1200

**Comment by BriungRi** [comment]
> yeah, this problem is annoying...fix is on the way #1199, or you might just pin the ethereum metrics exporter version as suggested in this PR #1200

Some additional thoughts. I think versions in this repo should be pinned in general. Pulling `latest` make this project setup less deterministic and can mean things break unexpectedly in the future. Perhaps if anything, a dependabot-like software could be used to bump things to newer versions.

**Comment by nflaig** [comment]
> Some additional thoughts. I think versions in this repo should be pinned in general. Pulling latest make this project setup less deterministic and can mean things break unexpectedly in the future

yeah thought about that too and as you mentioned it would require to automatically create PRs to bump the package versions similar to dappnode [bump-upstream github action](https://github.com/dappnode/DAppNodeSDK#github-actions).

Without the automatic bump of versions I think it would not be a good solution as the ecosystems evolves quickly and new releases are done frequently. There were als not that many issues due to using `latest`, I personally only had the ethereum metrics explorer problem.

@yorickdowne what do you think? I feel like we could easily implement this in eth-docker, might require to build a custom github action or just running a script might do the job as well

**Comment by yorickdowne** [comment]
@nflaig I am leaning towards leaving it at `latest` for CL/EL clients. An automated PR has the same risk: A client makes a breaking parameter change and users that upgrade have a non-working setup until they downgrade or eth-docker is updated. This has happened a couple times with Erigon. The other clients are pretty good at signalling changes before they become critical.

Inserting myself into this release pipeline like RocketPool and Stereum do is not something I want to do.

**Comment by nflaig** [comment]
@yorickdowne I agree with what you said, partially pinning seems like a good middle ground. However, one advantage to have fixed versions is that new releases could be rolled out to eth-docker users a bit later as the version bumps would not be merged automatically but have to be reviewed and merged manually. I would assume this approach would slightly improve the stability but I am not sure if it is worth the extra effort, especially because issues are fixed quite fast in eth-docker.

**Comment by yorickdowne** [comment]
OK good point about automated PRs that still need to be reviewed.

I think for now I'll stick with "partial pinning". It seems to work. It'd become an issue if clients start introducing breaking changes regularly without warning. So far, fingers crossed, that hasn't been the case.
