### ISSUE TITLE
Unable to remove validator using keys API

### ISSUE THREAD

**Issue by ColinCampbell** [eth-educators/eth-docker#1177]
Hey there! I'm attempting to move my staking setup from one machine to another. I've been planning on following the [Moving guide](https://eth-docker.net/Support/Moving/). I can list the key using `./ethd keys list` but when I run `./ethd keys delete 0xPUBKEYHERE` I receive the following error:
```
Creating ethstaker_validator-keys_run ... done
The key was found but an error was encountered trying to delete it:
Cannot remove read-only validator
```
I've looked through the code both in eth-docker and in Teku (which is my VC) and I can't seem to figure out a way to unlock to allow me to remove. Given this is a sensitive operation I figured I would ask before trying too many things.

**Comment by nflaig** [comment]
Hey @ColinCampbell, this seems to be a teku specific error message thrown, see [key manager readonly check](https://github.com/ConsenSys/teku/blob/89a410244992b9a10fd9c7f2e9d2d798a0fc22fe/validator/client/src/main/java/tech/pegasys/teku/validator/client/ActiveKeyManager.java#L133), I am not sure about the implementation details but I would suggest to ask this [their discord](https://discord.gg/7hPv2T6) in the [teku channel](https://discord.com/channels/697535391594446898/697539289042649190)

**Comment by yorickdowne** [comment]
This is indeed a Teku-ism. The validator was added with the legacy import method, before keymanager, and thus cannot be removed with keymanager.

This is what you can do:

`./ethd stop`
`sudo bash`
`cd /var/lib/docker/volumes/eth-docker_teku-data/_data`
Find the key in `validator-keys/` and the password in `validator-passwords/` and delete those files manually
`exit`
`./ethd start`

**Comment by ColinCampbell** [comment]
Thanks for the help, this worked perfectly!
