### ISSUE TITLE
Unexpected return code 413 on ethd import keys

### ISSUE THREAD

**Issue by caevv** [eth-educators/eth-docker#1201]
Failure to import keys.

```
./ethd keys import
[+] Running 1/1
 ⠿ Container eth-docker-consensus-1  Recreated                                                                                                                                        2.6s
[+] Running 1/1
 ⠿ Container eth-docker-consensus-1  Started                                                                                                                                          1.4s
WARNING - imported keys are immediately live. If these keys exist elsewhere,
you WILL get slashed. If it has been less than 15 minutes since you deleted them elsewhere,
you are at risk of getting slashed. Exercise caution

I understand these dire warnings and wish to proceed with key import (No/Yes) Yes
Please enter the password for your validator key(s):
Please re-enter the password:

Found slashing protection import file /validator_keys/slashing_protection.json for xxxxxx
It will be imported
Unexpected return code 413. Result:
```

No error message, just that code. The password is correct 100%.

**Comment by nflaig** [comment]
which CL client are you using?

**Comment by caevv** [comment]
nimbus + geth

**Comment by nflaig** [comment]
A 413 error code indicates that the payload is too big. In your case, looks like the `slashing_protection.json` file is the issue, by default nimbus only allows ~16MB.

You should be able to resolve this issue by providing `--rest-max-body-size` to `CL_EXTRAS` in your `.env` file
https://github.com/eth-educators/eth-docker/blob/d1e21eb86f60cc7c9f57a9b845a1880faa38a255/default.env#L96

For example

```sh
CL_EXTRAS=--rest-max-body-size 65536
```

what value you need to provide here really depends on the size of your slashing protection files

**Comment by caevv** [comment]
Thanks, I managed to get past that error, but then I got a different one related to this:
https://pullanswer.com/questions/nimbus-cannot-import-a-keystore-exported-from-prysm

I gave up nimbus and now I'm trying lighthouse, but another error now:
```
curl: (7) Failed to connect to validator port 7500 after 0 ms: Connection refused
Error encountered while trying to call the keymanager API via curl.
Please make sure validator is up and shows the key manager API, port 7500, enabled.
Error code 7
```

I'm not sure if there is something related, but every time I `ethd up` lighthouse is recreated. 

```
$ ethd keys import # or even ethd keys list
curl: (7) Failed to connect to validator port 7500 after 0 ms: Connection refused
Error encountered while trying to call the keymanager API via curl.
Please make sure validator is up and shows the key manager API, port 7500, enabled.
Error code 7
```

**Comment by nflaig** [comment]
> I gave up nimbus and now I'm trying lighthouse, but another error now:

looks like the validator client is not running

> I'm not sure if there is something related, but every time I ethd up lighthouse is recreated.

I noticed that as well on my setup, not sure why this happens I thought it might be something isolated to my environment

What you might wanna do is `ethd down` and then run `ethd up` again.

If you are planning to switch CL client from Prysm to something else, I would highly recommend Lodestar. It is really stable and has relatively low resource usage + best of all, it is a minority client so you reduce your slashing risk.

**Comment by caevv** [comment]
I went with Lighthouse only because the RAM usage is very low. I run a few things together with the staking.
I think it will work now, `key list` is working. Just holding my horses and researching a bit about `Lodestar`.
https://eth-docker.net/Usage/ResourceUsage

**Comment by nflaig** [comment]
> I went with Lighthouse only because the RAM usage is very low

Lighthouse is a good choice as well, especially if you have resource restrictions, the only concern is that it has [too high % of the network share](https://clientdiversity.org/) which means you increase your slashing risk in case of a consensus failure

> Just holding my horses and researching a bit about Lodestar

Sure, I would generally recommend to use the client you feel most comfortable with. eth-docker allows to switch the CL quite easily, assuming there are no strange issues like you the one you just had with importing the slashing protection...

Definitely let me know if you have any questions regarding Lodestar, running it for months now it and works well even on a really slow network. https://eth-docker.net/Usage/ResourceUsage says that RAM usage is around 4GB but it is mostly around 3GB.

**Comment by caevv** [comment]
Is there a lodestar `rest-max-body-size` equivalent?

```
Unexpected return code 413. Result: {"statusCode":413,"code":"FST_ERR_CTP_BODY_TOO_LARGE","error":"Payload Too Large","message":"Request body is too large"}
```

**Comment by nflaig** [comment]
> Is there a lodestar rest-max-body-size equivalent?

yes there is, there is no real risk setting this to a really high value, e.g. 120 MB

```sh
CL_EXTRAS='--keymanager.bodyLimit 125829120'
```

**Comment by caevv** [comment]
Many thanks for the help 👍

**Comment by nflaig** [comment]
Sure no problem, glad I was able to solve your issue 👍 

If you have any questions or issues with Lodestar feel free to join us on discord (https://discord.gg/b7cEJpVX) in the `lodestar-general` or `lodestar-help` channel.

**Comment by caevv** [comment]
I just tried with lodestar and I'm getting this: 
`Internal server error. Error: Maximum call stack size exceeded`

Running with:
`VC_EXTRAS='--keymanager.bodyLimit 11125829120'`
