### ISSUE TITLE
failing startup

### ISSUE THREAD

**Issue by HannanSolo** [eth-educators/eth-docker#1208]
When I start up my node with `ethd start` the node explorer container fails to start up.

This is my error.

```
 ⠴ Container eth-docker-node-exporter-1              Starting                                                                                                0.5s
Error response from daemon: path / is mounted on / but it is not a shared or slave mount
```

**Comment by yorickdowne** [comment]
Which OS is this? For macOS there is a `grafana-rootless.yml` to avoid this error message, ditto for rootless docker installs.
