### ISSUE TITLE
./ethd wont install 

### ISSUE THREAD

**Issue by 0XFEZ** [eth-educators/eth-docker#1209]
I've switched to nonroot user and it says permission denied, if I try to run as root it says please install as non-root user

**Comment by yorickdowne** [comment]
Permission denied for what, exactly? Please come to ethstaker Discord to troubleshoot this.

**Comment by yorickdowne** [comment]
One quick comment: You want that non-root user to be part of the `sudo` and `docker` groups, if this is a Debian-based distro like Ubuntu.
