### ISSUE TITLE
Issue with YAML parsing

### ISSUE THREAD

**Issue by rom-mat** [eth-educators/eth-docker#1235]
Hello,
after syncing the last commit and updating, I have the following error using either `ethd update` or `ethd stop` or `ethd up` : 
yaml: line 168: did not find expected key

I'm not sure to identify where it comes from and the logs are not very verbose. Any hint to start debugging ?

**Comment by yorickdowne** [comment]
Hey sorry for breaking things! Please give me your `COMPOSE_FILE` from `.env` and I will see that I can reproduce this!

Does it tell you more around that, like which yaml file?

**Comment by yorickdowne** [comment]
The only two yml files that even have that many lines are `lighthouse.yml` and `prysm.yml`. I cannot reproduce with either.

Maybe you have local changes to files? What does `git status` show you?

**Comment by rom-mat** [comment]
Yes I do have some changes which I re-apply at every release from the main branch.
This time there was an issue apparently. so I removed several YAML files, and `git restore` them.
The error has disappeared now but it's quite strange because I didn't change anything to my process. Maybe a yaml file didn't sync well. I'll close the issue. thanks for your quick answer.

**Comment by yorickdowne** [comment]
One thing I'll point out is that `CL_EXTRAS`, `EL_EXTRAS` and `VC_EXTRAS` exist in `.env` and cover a lot of use cases that might otherwise be handled by yml changes.

Where you do need changes, if you commit them, they should merge automatically with the next update
