### ISSUE TITLE
DOPPELGANGER missing in teku

### ISSUE THREAD

**Issue by alepacheco** [eth-educators/eth-docker#1250]
Hi, this feature is not enable on teku but it can be configured with this parms. 

https://docs.teku.consensys.net/HowTo/Doppelganger-Detection

> # Enable doppelganger detection
> Enable doppelganger detection by setting the [--doppelganger-detection-enabled](https://docs.teku.consensys.net/Reference/CLI/CLI-Syntax#doppelganger-detection-enabled) option to true.
> Your validator client must be connected to a beacon node with validator liveness tracking enabled. Enable validator liveness tracking by setting the [--beacon-liveness-tracking-enabled](https://docs.teku.consensys.net/Reference/CLI/CLI-Syntax#beacon-liveness-tracking-enabled) option to true.

**Comment by yorickdowne** [comment]
This feature has been added. Thanks for the suggestion!

**Comment by yorickdowne** [comment]
So I did. Adding this now. Thanks!
