### ISSUE TITLE
MEV boost failing

### ISSUE THREAD

**Issue by slipperybeluga** [eth-educators/eth-docker#1273]
Hello,

I am running a teku/erigon eth-docker node with MEV boost enabled ( eth-docker v2.2.6.3). I didn't see any changelogs regarding security updates or mev boost so I have not updated yet. I have over 99% uptime however I find that my node is having a hard time staying connected to the mev boost relays. I have several selected in the .env file and find that after several hours or a day of running the node, teku gives the following error in the logs:

> The builder is not available: {"code":503,"message":"all relays are unavailable"}. Block production will fallback to the execution engine.

If I restart the container, I usually get a success message for the relays in the log:

> [...] registration(s) were successfully sent to the builder network via the Beacon Node.

This is particularly frustrating as an independent node operator. I have only a couple blocks to my name and they each have gotten < 10% of the rewards of neighboring blocks because of this failure. Any ideas? Is this a potential issue with my .env file? My relays listed in the .env file are comma separated but I noticed that the COMPOSE_FILE line is colon separated. 

eg:

>COMPOSE_FILE=teku.yml:erigon.yml:grafana.yml:grafana-shared.yml:mev-boost.yml

>MEV_RELAYS=https://0xa15b52576bcbf1072f4a011c0f99f9fb6c66f3e1ff321f11f461d15e31b1cb359caa092c71bbded0bae5b5ea401aab7e@aestus.live,https://0x98650451ba02064f7b000f5768cf0cf4d4e492317d82871bdc87ef841a0743f69f0f1eea11168503240ac35d101c9135@mainnet-relay.securerpc.com,https://0x8b5d2e73e2a3a55c6c87b8b6eb92e0149a125c852751db1422fa951e42a09b82c142c3ea98d0d9930b056a3bc9896b8f@bloxroute.max-profit.blxrbdn.com

**Comment by yorickdowne** [comment]
This is unrelated to the format of `.env`. All relays have been struggling the past two days. You can add more relays and see whether that helps. A list is at https://ethstaker.cc/mev-relay-list/

When you `./ethd logs -f mev-boost` you should see it connect to relays, and give you a list of configured relays on startup
