### ISSUE TITLE
./ethd update fails with: failed to solve: process "/bin/sh -c set -eux 

### ISSUE THREAD

**Issue by alepacheco** [eth-educators/eth-docker#1321]
Hi, I have been running eth-docker for a while and now i am getting this error when i tried to update. I also pruned docker and updated to the latest version but the issue persist.
Docker version: 23.0.4

<img width="1439" alt="Screenshot 2023-04-18 at 15 30 58" src="https://user-images.githubusercontent.com/8210939/232793455-ca3b2ff7-7727-490a-a29c-605ec83f9d04.png">

**Comment by yorickdowne** [comment]
This says it couldn’t get the Ubuntu archive. This may have been a temporary issue with network connectivity. This is easier to troubleshoot interactively on discord
