### ISSUE TITLE
Issue with ./ethd keys prepare-address-change 

### ISSUE THREAD

**Issue by sturmE** [eth-educators/eth-docker#1332]
To start, I updated by running 

```
$ ./ethd update
```

Then 

```
$ ./ethd down
$ ./ethd up
```

Following along here, https://eth-docker.net/Support/ChangingWithdrawalCredentials, I ran

```
$ ./ethd keys list
```

Which succeeded in printing out my validator addresses.

I then ran 

```
$ ./ethd keys prepare-address-change
Generating offline prep file
offline-preparation.json generated
The preparation file has been copied to ./.eth/ethdo/offline-preparation.json
It contains 597444 validators.
Please verify that this matches what you see on https://beaconcha.in/validators

Downloading ethdo

Copy the contents of ./.eth/ethdo to a USB drive, and prepare a Linux Live USB to safely enter your mnemonic.
Please see https://eth-docker.net/Support/ChangingWithdrawalCredentials for details
```

As you can see, it listed out quite a few validators. I have a few less than 597444. 

Some additional notes. This is a vc only setup and I am using Lighthouse.

**Comment by yorickdowne** [comment]
This is exactly as expected. The offline prep json contains all validators on the chain, so ethdo can just scan the mnemonic and does not need to know your validators while prepping.

**Comment by yorickdowne** [comment]
Side note, after an update, all you need is ./ethd up. Try it next time. It’ll restart just the changed services.
