### ISSUE TITLE
Don't ask for fee recipient when setting up Ethereum RPC node

### ISSUE THREAD

**Issue by PabloCastellano** [eth-educators/eth-docker#1343]
During configuration, if you choose to setup an Ethereum RPC node (consensus and execution client, but no validator client) you are forced to enter a valid fee recipient while this parameter is only useful when setting up a validator client. Same for MEV-boost relays.

![image](https://user-images.githubusercontent.com/73274/234418315-e5209a0e-c75c-4fb7-a3eb-0e36de680b20.png)

![image](https://user-images.githubusercontent.com/73274/234417978-dd1194e3-0010-4984-bced-98dc3a413e45.png)

![image](https://user-images.githubusercontent.com/73274/234418027-634e69b8-cbe1-4dc0-9bb5-10a115b6b4bd.png)

**Comment by yorickdowne** [comment]
Yep. This is by design. A VC can be connected, and this way there is a fallback. As well, some clients output a warning message if this is not set.

Setting a fee recipient is entirely harmless if you don't connect a VC. You can set it to absolutely anything.

**Comment by yorickdowne** [comment]
You have a point though, this question keeps coming up. I changed the language so it's a little clearer as to what's going on.
