### ISSUE TITLE
Ampersand in Graffiti is incorrectly replaced

### ISSUE THREAD

**Issue by davidkassa** [eth-educators/eth-docker#1360]
If you set your graffiti with an ampersand (&) it'll get updated with an injected property
`GRAFFITI=Hamm 🐖 GRAFFITI=🦉eth-docker🦉 Pua 🐷 ⌐◨-◨	      |	GRAFFITI=Hamm 🐖 & Pua 🐷 ⌐◨-◨`
Escaping with a \ works but the escape character is then removed and needs to be re-added before every `./ethd up`
`GRAFFITI=Hamm 🐖 & Pua 🐷 ⌐◨-◨				      |	GRAFFITI=Hamm 🐖 \& Pua 🐷 ⌐◨-◨`

**Comment by yorickdowne** [comment]
Oh wow. Thanks! I'll need to dig to see what's doing that and what to do about it.

**Comment by yorickdowne** [comment]
Try again, please. It should be fixed.

**Comment by davidkassa** [comment]
worked -- thanks!
