### ISSUE TITLE
I created a grafana dashboard for logs - how do I contribute?

### ISSUE THREAD

**Issue by gorillamania** [eth-educators/eth-docker#1381]
When I saw that Loki was integrated, I created a simple Grafana dashboard that displays the last x minutes of the important log files. I find it very handy for getting a quick view of what is going on. It also allows for searching by date, which is useful when trying to figure out why there was downtime at a particular time, seeing them all at once for a given timeframe.

Here's a screenshot.
<img width="1419" alt="Screenshot 2023-05-05 at 10 30 50 AM" src="https://user-images.githubusercontent.com/142708/236526695-3ff1a844-2dfc-4ad3-9584-4792d5f141d5.png">

I'd like to know how to best contribute this, so that it becomes part of eth-docker. If someone can give me a pointer on how the grafana dashboards are handled, I will create a pull request.

**Comment by yorickdowne** [comment]
The grafana Dashboards are loaded with a shell script when grafana starts. You could either place this as a json into the grafana folder, have the Dockerfile bring it in and the shell script load it; or if your dashboard is published somewhere, then just have the shell script grab it by the url.

**Comment by gorillamania** [comment]
I tested this with a clean install btw.
