### ISSUE TITLE
Cloudflare DDNS issues

### ISSUE THREAD

**Issue by nflaig** [eth-educators/eth-docker#1396]
Cloudflare DDNS no longer works for me, possibly related to

- https://github.com/eth-educators/eth-docker/pull/1338

and changes done here

- https://github.com/eth-educators/eth-docker/pull/1349

---

These are the values (with replacements) set in my .env file

> .env
```
DOMAIN=example.com
ACME_EMAIL=example@mail.com
CF_DNS_API_TOKEN=<token>
CF_ZONE_API_TOKEN=
CF_ZONE_ID=
DDNS_SUBDOMAIN=
DDNS_PROXY=true
```

Container logs

> cf-ddns-v4-1 logs
```
[2023-05-15A11:15:00+0000] INFO (992): Cloudflare DDNS start
[2023-05-15A11:15:07+0000] INFO (992): Started creating.
[2023-05-15A11:15:09+0000] ERROR (992): Failed to update .example.com. (Api Error from Cloudflare. Errors:
{"code":1004,"message":"DNS Validation Error","error_chain":[{"code":9000,"message":"DNS name is invalid."}]})
[2023-05-15A11:15:09+0000] INFO (992): Cloudflare DDNS end
```

---
Commit: `a90a8023d8fbb3b5bcde4430aee8a3852af436f2`
Version: `cloudflare-ddns@3.0.1`

**Comment by yorickdowne** [comment]
Ah yes. Crud. Damned if you do damned if you don't. This is currently designed to have a non-empty `DDNS_SUBDOMAIN`.

There's no good UX here I think ... if I remove the dot, then DDNS_SUBDOMAIN has to end in one, which is not at all intuitive. If I keep it, it needs to be not empty.

**Comment by yorickdowne** [comment]
Thank you for the report. I've changed the docs to point out that this no longer works for subdomains, and `./ethd update` should refuse an empty `DDNS_SUBDOMAIN`

**Comment by yorickdowne** [comment]
Yep exactly. Any name at all will work, and then point your CNAMEs there.
