### ISSUE TITLE
`./ethd install` fails when docker is not installed

### ISSUE THREAD

**Issue by tmke8** [eth-educators/eth-docker#1404]
This seems to be because in `ethd`, `determine_sudo` is always called which runs
```
systemctl status docker >/dev/null
```
which fails if docker is not installed.

**Comment by yorickdowne** [comment]
Yikes. Thanks for pointing that out! That's embarrassing. Let me see.

**Comment by yorickdowne** [comment]
Can I have you `git pull` and try that again, please

**Comment by tmke8** [comment]
Ah, I already commented out `determine_sudo` locally with vim, and then it ran fine for me. I only reported this issue afterwards so that others wouldn't face the same issue.
