### ISSUE TITLE
ethd not working on macOS: `systemctl` command not found

### ISSUE THREAD

**Issue by jimmygchen** [eth-educators/eth-docker#1423]
I'm aware that macOS isn't the best OS to run `eth-docker`, I'm mainly doing stuff on macOS for testing, however I noticed that latest version of `ethd` no longer works on macOS with introduction of `systemctl`:

```
❯ ./ethd config
./ethd: line 40: systemctl: command not found
```
ps. not an urgent issue on my side and I'm ok to use it in Linux, but happy to help with testing a fix if you plan to continue macOS support.

This still works in `v2.2.10.1`.

**Comment by yorickdowne** [comment]
Thank you for that! This should be fixed now. If you see further macOS issues, please let me know.
