### ISSUE TITLE
cf-ddns-v4/v6 CPU causes 100% CPU usage 24/7

### ISSUE THREAD

**Issue by nflaig** [eth-educators/eth-docker#1431]
- See https://github.com/joshuaavalon/docker-cloudflare/issues/79

Just reporting this back here to consider disabling container until this is fixed, it caused my CPU temp to drastically increase to almost 100°C.

**Comment by nflaig** [comment]
Looks like it is not required to run 2 containers for v4 and v6, see https://github.com/joshuaavalon/docker-cloudflare/issues/79#issuecomment-1598035475.

**Comment by yorickdowne** [comment]
Interesting. I'll take a look to run just one container

**Comment by yorickdowne** [comment]
Thanks for digging into this with the dev of cf-ddns. I've combined v4/6 into one container

**Comment by yorickdowne** [comment]
CPU temp sounds more like a hardware issue. Power Level 1/2 should be set for a NUC, to TDPlow for the CPU and ~1.25x that. While cf-ddns shouldn't take 100% CPU; similarly the hardware shouldn't overheat when CPU is maxed for a long time.

**Comment by nflaig** [comment]
> CPU temp sounds more like a hardware issue. Power Level 1/2 should be set for a NUC, to TDPlow for the CPU and ~1.25x that.

Thanks, will look into this

**Comment by yorickdowne** [comment]
Can you see whether 3.1.0 resolves this in your environment? A simple ./ethd update should bring it in

**Comment by nflaig** [comment]
> Can you see whether 3.1.0 resolves this in your environment?

Already deployed 3.1.0 but it will be hard to confirm if it fixes the issue, it has been really inconsistent for me as well.

**Comment by nflaig** [comment]
Closing as the issue will be fixed with cloudflare-ddns v3.2.1

**Comment by yorickdowne** [comment]
Mayyyybe fixed. Turns out cloudflare-ddns had a bug and stopped updating records. So fixed bcs fixed or fixed bcs it stopped doing work?

**Comment by nflaig** [comment]
This doesn't sound good https://github.com/joshuaavalon/docker-cloudflare/issues/79#issuecomment-1649756626 though.

**Comment by yorickdowne** [comment]
The answer may be to investigate https://github.com/timothymiller/cloudflare-ddns. Just sticking this here for reference for now.

**Comment by yorickdowne** [comment]
No particularly good choices here. Go with another image that has some missing features, or try and fix the existing image, as the dev won't.

"This docker is just cron job running a Node.js script. If you see my replies above, my best guest is the related to base Docker image cron.

There are really nothing I can changed. You can try different base image to see anything different."

**Comment by nflaig** [comment]
I just have the container stopped at the moment and if my server IP changes I just start it a few minutes and stop it again which is sufficient to update the dns records. This works for me but requires additional effort to have it automated.

**Comment by yorickdowne** [comment]
Well, we need a new idea. "This repository has been archived by the owner on Jan 28, 2024"

**Comment by yorickdowne** [comment]
@nflaig You're probably the heaviest user here. I am pondering introducing a `CF_ZONE_ID` variable, populating it during `./ethd update` for existing users, and getting rid of the requirement to have `Zone.Zone:Read` and `Zone.Zone Settings: Read`  permissions across all Zones. Arguably UX is no worse when requiring the ID, and security is better.

Thoughts?

**Comment by nflaig** [comment]
> Thoughts?

Sounds good to me, I just have a single zone in the cf account I use for this but it's generally good idea to limit permissions to a minimum.

**Comment by yorickdowne** [comment]
This is in. IPv4 only right now since upstream doesn't have `ipv4-and-ipv6` yet. That's coming: https://github.com/qdm12/ddns-updater/issues/507

**Comment by yorickdowne** [comment]
Turns out traefik wants those permissions, so I don't have a way around that right now
