### ISSUE TITLE
Dangling images

### ISSUE THREAD

**Issue by synthic** [eth-educators/eth-docker#1446]
Do you think it would be a good idea to add a `docker image prune` into the update script somewhere? Whenever I run the update command a bunch of dangling/untagged images always seem to be left over and I have to remove them manually.

**Comment by yorickdowne** [comment]
There already is a `docker system prune` in `./ethd update`. Going further than that is likely not worth it. I just tried it on a machine that was recently updated, and it freed: `Total reclaimed space: 21.19MB`

I'll call that good enough :)
