### ISSUE TITLE
prysm-consensus:local  Restarting (132)

### ISSUE THREAD

**Issue by marbew** [eth-educators/eth-docker#1457]
Hey guys, I just followed the guideline to run eth-docker with geth and prysm, but prysm gives me this error:
`2023-07-27T23:21:59.329918352Z MEV Boost enabled
2023-07-27T23:21:59.330871703Z Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.
2023-07-27T23:22:59.834229991Z Checkpoint sync enabled
2023-07-27T23:22:59.834267921Z MEV Boost enabled
2023-07-27T23:22:59.835220399Z Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.
`
Any quick suggestion please?

All other containers are all up and running.
CONTAINER ID   IMAGE                                      COMMAND                  CREATED          STATUS                            PORTS                                                                                                         NAMES
a7beae799555   grafana/promtail:latest                    "./etc/promtail/entr…"   49 minutes ago   Up 49 minutes                                                                                                                                   eth-docker-promtail-1
f52dccb06efb   gcr.io/cadvisor/cadvisor                   "/usr/bin/cadvisor -…"   49 minutes ago   Up 49 minutes (healthy)           8080/tcp                                                                                                      eth-docker-cadvisor-1
9a69855818ce   mev-boost:local                            "/app/mev-boost -add…"   49 minutes ago   Up 49 minutes                     18550/tcp                                                                                                     eth-docker-mev-boost-1
cf509ae62a90   prom/node-exporter:latest                  "/bin/node_exporter …"   49 minutes ago   Up 49 minutes                     9100/tcp                                                                                                      eth-docker-node-exporter-1
bb7b3c7d73a1   grafana:local                              "provision-dashboard…"   49 minutes ago   Up 49 minutes                     0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                                                     eth-docker-grafana-1
4f5cbb209aa0   prysm-consensus:local                      "docker-entrypoint.s…"   49 minutes ago   Restarting (132) 43 seconds ago                                                                                                                 eth-docker-consensus-1
6dce557f0b5e   nbarrientos/cryptowat_exporter             "/bin/sh -c './bin/c…"   49 minutes ago   Up 49 minutes                     9745/tcp                                                                                                      eth-docker-cryptowat-exporter-1
90ad7786b90a   prom/blackbox-exporter:master              "/bin/blackbox_expor…"   49 minutes ago   Up 49 minutes                     9115/tcp                                                                                                      eth-docker-blackbox-exporter-1
85eb7aefbada   ethereum-metrics-exporter:local            "docker-entrypoint.s…"   49 minutes ago   Up 49 minutes                                                                                                                                   eth-docker-ethereum-metrics-exporter-1
aa7d54566d21   geth:local                                 "docker-entrypoint.s…"   49 minutes ago   Up 49 minutes                     8545-8546/tcp, 0.0.0.0:30303->30303/tcp, 0.0.0.0:30303->30303/udp, :::30303->30303/tcp, :::30303->30303/udp   eth-docker-execution-1
6a49d987939b   grafana/loki:latest                        "/usr/bin/loki --con…"   49 minutes ago   Up 49 minutes                     3100/tcp                                                                                                      eth-docker-loki-1
d6325774914a   prometheus:local                           "choose-config.sh /b…"   49 minutes ago   Up 49 minutes                     9090/tcp                                                                                                      eth-docker-prometheus-1
9111d95e98cc   prometheuscommunity/json-exporter:latest   "/bin/json_exporter …"   49 minutes ago   Up 49 minutes                     7979/tcp                                                                                                      eth-docker-json-exporter-1

**Comment by yorickdowne** [comment]
SIGILL would usually mean you need a portable version of Prysm, that is, this is an old(er) CPU. However, I do not see a portable version on their docker hub registry.

I'd raise this with the Prysm team, with the CPU make/model you're using and the Prysm version that fails.

**Comment by marbew** [comment]
BEELINK U59 - https://www.bee-link.net/products/u59-n5095
ubuntu@beenode:~/eth-docker$ cat /proc/cpuinfo  | grep 'name'| uniq
model name	: Intel(R) Celeron(R) N5105 @ 2.00GHz
ubuntu@beenode:~/eth-docker$ uname -a
Linux beenode 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@beenode:~/eth-docker$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
ubuntu@beenode:~/eth-docker$ ./ethd version
This is eth-docker v2.3.1

Error response from daemon: Container 4f5cbb209aa09a2c7cb93dc70f0e29ab4cec29bf819863d713542cc938861b74 is restarting, wait until the container is running

Let me know if you need more info. Thanks

**Comment by yorickdowne** [comment]
Yep the Celeron’s are missing some instructions. You’ll want to let the Prysm team know that this Celeron causes a SIGILL with their client and see whether they’re interested in creating a portable version of the software, that works on older CPUs or CPUs otherwise missing parts of the instruction set such as Celerons.

**Comment by marbew** [comment]
How can I get the prysm version on the eth-docker setup? Please I get only the local tag

**Comment by yorickdowne** [comment]
Inside .env is the tag you’re using, search for PRYSM_DOCKER in that file.

**Comment by marbew** [comment]
Changing the suggested tag with: v4.0.7-portable started to run properly. Now I really need to understand how to managed when new version are available? Any suggestion. CHeers

**Comment by marbew** [comment]
ubuntu@beenode:~/eth-docker$ grep "PRYSM_DOCKER" .env
#PRYSM_DOCKER_TAG=stable
PRYSM_DOCKER_TAG=v4.0.7-portable
PRYSM_DOCKER_VC_TAG=stable
PRYSM_DOCKERFILE=Dockerfile.binary

Did not work. Same error.

**Comment by marbew** [comment]
How do I see which image is it? I am dealing with prysm people on Discord? Are you on a discord channel?

**Comment by marbew** [comment]
Also changing to 
PRYSM_DOCKER_TAG=v4.0.7-portable
PRYSM_DOCKER_VC_TAG=v4.0.7-portable

Does not work either. Any other suggestion apparently even prysm people on discord are struggling with this one.

**Comment by marbew** [comment]
How can I be sure that after changing that tag, then running ./ethd restart I do have that used. The running/crashing container still showing :local as tag

**Comment by yorickdowne** [comment]
After changing a tag, ./ethd update builds the local image so it gets used. Then an ./ethd up uses the changed tag.

If there is a latest-portable you could use that, otherwise you’d update the specific version portable tag as new versions are released and whenever you want them.

**Comment by marbew** [comment]
All works now. Thanks for the steps to follow to build local image.
