### ISSUE TITLE
Shellcheck fails with current ethd script

### ISSUE THREAD

**Issue by haurog** [eth-educators/eth-docker#1491]
It is impossible for me to change anything in ethd as the pre-commit hooks fail due to errors in pre-existing code. The error message is the following: 
```
Test shell scripts with shellcheck..........................................Failed
- hook id: shellcheck
- exit code: 1

In ethd line 1307:
    __path=''
    ^----^ SC2034: __path appears unused. Verify use (or export if used externally).


In ethd line 1310:
        __prysm=1
        ^-----^ SC2034: __prysm appears unused. Verify use (or export if used externally).

For more information:
  https://www.shellcheck.net/wiki/SC2034 -- __path appears unused. Verify use...
```
The lines in question seem to be remnants of a non-finished wagyu implementation from 19 months ago. They seem not to be needed anymore. Can I delete them?

**Comment by yorickdowne** [comment]
Yeah go ahead, they serve no purpose now

**Comment by yorickdowne** [comment]
#1493 should close this
