### ISSUE TITLE
Feature request: specify datadir for containers

### ISSUE THREAD

**Issue by mondsen** [eth-educators/eth-docker#1557]
**Rationale:** I have my node running on a small PC with an SSD for operating system and one large SSD specifically for staking purposes. I use my server at home for multiple docker containers. It is desired for me to have every container except for staking on the operating system SSD while only the ETH staking data is on the large SSD. This cannot be achieved currently, the only option is to either

- move the docker root directory for all containers
- manually edit all yml files that I need for a mapping

**Proposal:** Specify mappings from the .env file in all yml files to map the docker volume to a desired directory. Example for Prysm:

Currently:
````    
volumes:
      - prysmconsensus-data:/var/lib/prysm
````
Proposal:
````
volumes:
      - ${prysmdatadir}:/var/lib/prysm
````

This would affect all yml files. For me, only the big ones would be important which require a lot of space, meaning consensus and execution clients. Everything else can stay as is (to ease setup process for the user).

**Comment by yorickdowne** [comment]
I am not going to go for bind mounts, volumes have a lot going for them including the ease of permissions and ease to remove them. The docker data root can be adjusted for those users that want docker volumes on a different drive

**Comment by ulope** [comment]
Why would you not let the user make this choice?

**Comment by yorickdowne** [comment]
Because I can’t. It’s either bind mounts or named volumes. I have to make a choice, and the one I made works well and has advantages.

That said making that change to your local file and committing that locally is easy.
