### ISSUE TITLE
Siren INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by davidkassa** [eth-educators/eth-docker#1560]
I'm consistently getting a Network Error because Siren failed to maintain connection to the Beacon Node. When I look at the console, I'm getting 500 responses and CORS errors connecting to the /logs endpoints. With the message "INTERNAL_SERVER_ERROR: SSE Logging is not enabled".

Per the Lighthouse Discord and their docs: 
you need to run the beacon node with --gui

**Comment by davidkassa** [comment]
https://lighthouse-book.sigmaprime.io/ui-configuration.html

**Comment by yorickdowne** [comment]
I already had `--http` and `--validator-monitor-auto` which is why I didn't use this. I don't see another way to enable SSE logging, so let's give that a whirl: I removed the individual flags and replaced them with `--gui`. Test again, please, and let me know how it behaves.

**Comment by davidkassa** [comment]
This solved the bulk of the issues and makes Siren usable. There is still a single failure for both beacon and validator when the dashboard loads, but I don't imagine this is a flag issue. I'll let you know if their Discord mentions a potential solution.

**Comment by yorickdowne** [comment]
I am closing this. Thanks for the help testing Siren!

If there are further issues that benefit from changes in Eth Docker, please open a new issue.
