### ISSUE TITLE
Switching to Nethermind EL from Geth

### ISSUE THREAD

**Issue by unimos50** [eth-educators/eth-docker#1576]
Hi there, I'm trying to change from Geth to Nethermind following the steps provided here:
https://eth-docker.net/Support/SwitchClient#switching-the-execution-client-if-downtime-is-acceptable

Although I'm getting the following issue after checking the logs: `./ethd logs -f execution`

Output:
```
eth-docker-execution-1  | /usr/local/bin/docker-entrypoint.sh: line 59: /nethermind/nethermind: No such file or directory
eth-docker-execution-1  | /usr/local/bin/docker-entrypoint.sh: line 59: /nethermind/nethermind: No such file or directory
eth-docker-execution-1  | /usr/local/bin/docker-entrypoint.sh: line 59: /nethermind/nethermind: No such file or directory
eth-docker-execution-1  | /usr/local/bin/docker-entrypoint.sh: line 59: /nethermind/nethermind: No such file or directory
eth-docker-execution-1  | /usr/local/bin/docker-entrypoint.sh: line 59: /nethermind/nethermind: No such file or directory
eth-docker-execution-1  | /usr/local/bin/docker-entrypoint.sh: line 59: /nethermind/nethermind: No such file or directory
eth-docker-execution-1 exited with code 127
```

Any idea what I'm missing or I could be doing wrong?

Thanks!

**Comment by yorickdowne** [comment]
Looks like you don't have the current version of Nethermind. Check its tag with `nano .env`, you expect to see `latest`. Then `./ethd update` and `./ethd up`, that should fix it.
