### ISSUE TITLE
 'keys delete all' command deletes only the first key

### ISSUE THREAD

**Issue by tomaswest** [eth-educators/eth-docker#1612]
My setup - default latest eth-docker env file, latest Geth v1.13.4, Lighthouse v4.5.0, web3signer (enabled in .env file and .yml file properly added). Have multiple validator keys loaded.

When I run './ethd keys delete all' command I get following error (sensitive data redacted):

```
root@<host>:/home/tom/eth-docker# ./ethd keys delete all
[+] Creating 2/0
 ✔ Container eth-docker-consensus-1  Running                                                   0.0s
 ✔ Container eth-docker-validator-1  Running                                                   0.0s
WARNING - this will delete all currently loaded keys from web3signer and the validator client.

Do you wish to continue with key deletion? (No/yes) yes
Remote registration for validator 0x<PUBLIC KEY> deleted.
Validator 0x<PUBLIC KEY>  deleted.
Slashing protection data written to .eth/validator_keys/slashing_protection-0x<PUBLIC KEY>.json
Unexpected return code 404. Result: <html><body><h1>Resource not found</h1></body></html>

./ethd failed with error 1 on line 15

Please save the logs and come to Ethstaker Discord to troubleshoot this.

This happened during ./ethd delete delete all
```

As a result a first key is deleted properly and slashing file is written too, but I need to repeat that command multiple times to delete all keys.

**Comment by yorickdowne** [comment]
Please give me your `COMPOSE_FILE` in `.env` so I can attempt to reproduce this.

And thank you for the report.

**Comment by yorickdowne** [comment]
This should be fixed now. It works in my testing. Please `./ethd update` and try again.

**Comment by tomaswest** [comment]
It works for me now. Thanks
