### ISSUE TITLE
make use of semvers and allow rollback

### ISSUE THREAD

**Issue by salanfe** [eth-educators/eth-docker#1629]
First of all, big thanks for Eth Docker, amazing project !

yesterday, I ran `ethd update` and `ethd up` and my teku client went down. It was down for about 10 minutes in total, the time I figure out the issue and fix it. Luckily, I'm used to troubleshooting systems in production and didn't panic 😄 

The cause of the incident was the following:

- a few weeks ago, in my `.env`, I have replaced the line `TEKU_SRC_BUILD_TARGET='$(git describe --tags $(git rev-list --tags --max-count=1))'` by `TEKU_SRC_BUILD_TARGET=23.10.0` because I'm used to controlling which version I'm running. And I don't want to magically pull the latest one.
- meanwhile, [teku 23.11.0](https://github.com/Consensys/teku/releases/tag/23.11.0) got released yesterday
- and @yorickdowne being faster than light, immediately updated Eth Docker with a new flag for teku in this PR https://github.com/eth-educators/eth-docker/pull/1625
- so later that day, when I ran `ethd update` and `ethd up`, the following happened:
- `ethd update` runs `git pull` behind the scene (I think here https://github.com/eth-educators/eth-docker/blob/main/ethd#L1016) which pulled the latest changes of Eth Docker `main` branch, including the PR https://github.com/eth-educators/eth-docker/pull/1625 introducing the new flag `--checkpoint-sync-url` which is only supported by teku `23.11.0` (there's no documentation for that flag in the `23.10.0` doc https://docs.teku.consensys.net/23.10.0/reference/cli)
- I then ran `ethd up` and because I have fixed my teku to `23.10.0`, things started to break as the newly introduced flag `--checkpoint-sync-url` was not recognized by my teku `23.10.0`.
- luckily, I could quickly figure out that the flag was driven by `RAPID_SYNC_URL` and mitigate the issue.

this "incident" got me thinking about 2 things

1. being able to pass a semver (Eth Docker release tag) to the command: e.g. `ethd update --version=v2.3.8`
2. Implement a rollback logic.

a rollback logic could be
- as simple as: when running `ethd update`, just store the current git tag or git commit to an env var, and at the end of the script, print "To revert Eth Docker to the previously installed version, you may run `ethd update --version=vXX.YY.ZZ`", where `vXX.YY.ZZ` is the value in the env var.
- or as complex as: the "state" cloud maybe be stored in `.env` or another file. With that state, a rollback logic (very similar to `kubectl rollback` where the last 10 manifests are kept) could be implemented.

Obviously, I'm also to be blamed here. I should have tested those changes first before applying them on my server. Nonetheless, I think the ideas above could improve Eth Docker on the operational side of things. Although, we could also argue that the project is already quite complex and adding even more complexity isn't necessarily desirable.

cheers, and thanks again for the good work !

**Comment by yorickdowne** [comment]
Hmm interesting. So you're looking to pin the Eth Docker version while updating the clients.

I could do this with an `.env` variables for the Eth Docker version - `latest` or a specific tag. Let me think on it.

I haven't done semver because then I end up with version 112.x in rapid cadence :sweat_smile:

**Comment by salanfe** [comment]
Yeah I feel you 🤔 as an alternative to a semver, a commitSHA would also work. Although less user friendly, it would allow the same mechanism of being able to control which version of eth docker code base is being executed.

The command ethd update could then simply print "eth docker updated to commit XYZ from commit ABC. To revert, run ethd update --version=ABC".

Additionally, I'm also thinking: with your current defaults of pulling latest versions everywhere, if you go on vacation for 1-2 weeks and some clients meanwhile release breaking changes in their latest version, eth docker will be broken for everyone using those clients. So maybe you also want to print the clients version or commit sha as part of your script, to at least help debug issues (thinking out loud here)...

**Comment by yorickdowne** [comment]
OK so as an MVP you can now pin the version of Eth Docker. That by necessity only works from v2.3.9 onwards, as otherwise it'll go to a version that has no idea what pinning is.

**Comment by salanfe** [comment]
Sounds reasonable enough! Thanks for the great work 🚀
