### ISSUE TITLE
Failed to start beacon node

### ISSUE THREAD

**Issue by dani-s-92** [eth-educators/eth-docker#1642]
Hello,

I try to run a sepolia node with eth-docker. I am using this guides to run: https://taiko.xyz/docs/guides/run-a-sepolia-node and https://www.youtube.com/watch?v=7Lg_cY7iP2o

But if I try to run the node and check the logs with ./ethd logs -f consensus

And there is an error:
eth-docker-consensus-1  | Checkpoint sync enabled
eth-docker-consensus-1  | Lighthouse archive node without pruning
eth-docker-consensus-1  | Nov 23 08:24:00.128 INFO Logging to file                         path: "/var/lib/lighthouse/beacon/logs/beacon.log"
eth-docker-consensus-1  | Nov 23 08:24:00.129 INFO Lighthouse started                      version: Lighthouse/v4.5.0-441fc16
eth-docker-consensus-1  | Nov 23 08:24:00.129 INFO Configured for network                  name: sepolia
eth-docker-consensus-1  | Nov 23 08:24:00.129 INFO Data directory initialised              datadir: /var/lib/lighthouse
eth-docker-consensus-1  | Nov 23 08:24:00.129 INFO Deposit contract                        address: 0x7f02c3e3c98b133055b8b348b2ac625669ed295d, deploy_block: 1273020
eth-docker-consensus-1  | Nov 23 08:24:00.151 INFO Starting checkpoint sync                remote_url: https://holesky.beaconstate.info/, service: beacon
eth-docker-consensus-1  | Nov 23 08:24:00.151 INFO Blocks will be downloaded all the way back to genesis, service: beacon
eth-docker-consensus-1  | Nov 23 08:24:03.970 CRIT Failed to start beacon node             reason: Error loading checkpoint state from remote: InvalidSsz(OffsetSkipsVariableBytes(2736653))
eth-docker-consensus-1  | Nov 23 08:24:03.970 INFO Internal shutdown received              reason: Failed to start beacon node
eth-docker-consensus-1  | Nov 23 08:24:03.970 INFO Shutting down..                         reason: Failure("Failed to start beacon node")
eth-docker-consensus-1  | Failed to start beacon node
eth-docker-consensus-1  | Checkpoint sync enabled
eth-docker-consensus-1  | Lighthouse archive node without pruning
eth-docker-consensus-1  | Nov 23 08:25:04.350 INFO Logging to file                         path: "/var/lib/lighthouse/beacon/logs/beacon.log"
eth-docker-consensus-1  | Nov 23 08:25:04.350 INFO Lighthouse started                      version: Lighthouse/v4.5.0-441fc16
eth-docker-consensus-1  | Nov 23 08:25:04.351 INFO Configured for network                  name: sepolia
eth-docker-consensus-1  | Nov 23 08:25:04.351 INFO Data directory initialised              datadir: /var/lib/lighthouse
eth-docker-consensus-1  | Nov 23 08:25:04.351 INFO Deposit contract                        address: 0x7f02c3e3c98b133055b8b348b2ac625669ed295d, deploy_block: 1273020
eth-docker-consensus-1  | Nov 23 08:25:04.383 INFO Starting checkpoint sync                remote_url: https://holesky.beaconstate.info/, service: beacon
eth-docker-consensus-1  | Nov 23 08:25:04.384 INFO Blocks will be downloaded all the way back to genesis, service: beacon
eth-docker-consensus-1  | Nov 23 08:25:08.084 CRIT Failed to start beacon node             reason: Error loading checkpoint state from remote: InvalidSsz(OffsetSkipsVariableBytes(2736653))
eth-docker-consensus-1  | Nov 23 08:25:08.084 INFO Internal shutdown received              reason: Failed to start beacon node
eth-docker-consensus-1  | Nov 23 08:25:08.084 INFO Shutting down..                         reason: Failure("Failed to start beacon node")
eth-docker-consensus-1  | Failed to start beacon node
eth-docker-consensus-1  | Checkpoint sync enabled
eth-docker-consensus-1  | Lighthouse archive node without pruning
eth-docker-consensus-1  | Nov 23 08:26:08.441 INFO Logging to file                         path: "/var/lib/lighthouse/beacon/logs/beacon.log"
eth-docker-consensus-1  | Nov 23 08:26:08.442 INFO Lighthouse started                      version: Lighthouse/v4.5.0-441fc16
eth-docker-consensus-1  | Nov 23 08:26:08.442 INFO Configured for network                  name: sepolia
eth-docker-consensus-1  | Nov 23 08:26:08.443 INFO Data directory initialised              datadir: /var/lib/lighthouse
eth-docker-consensus-1  | Nov 23 08:26:08.443 INFO Deposit contract                        address: 0x7f02c3e3c98b133055b8b348b2ac625669ed295d, deploy_block: 1273020
eth-docker-consensus-1  | Nov 23 08:26:08.468 INFO Starting checkpoint sync                remote_url: https://holesky.beaconstate.info/, service: beacon
eth-docker-consensus-1  | Nov 23 08:26:08.468 INFO Blocks will be downloaded all the way back to genesis, service: beacon
eth-docker-consensus-1  | Nov 23 08:26:12.251 CRIT Failed to start beacon node             reason: Error loading checkpoint state from remote: InvalidSsz(OffsetSkipsVariableBytes(2736653))
eth-docker-consensus-1  | Nov 23 08:26:12.251 INFO Internal shutdown received              reason: Failed to start beacon node
eth-docker-consensus-1  | Nov 23 08:26:12.251 INFO Shutting down..                         reason: Failure("Failed to start beacon node")
eth-docker-consensus-1  | Failed to start beacon node

Can someone tell me what the issue is here? How can I solve this:

**Comment by yorickdowne** [comment]
```
eth-docker-consensus-1 | Nov 23 08:24:00.151 INFO Starting checkpoint sync remote_url: https://holesky.beaconstate.info/, service: beacon
```

And you are on Sepolia. You can't checkpoint-sync Sepolia from a Holeksy checkpoint server :sweat_smile:

**Comment by dani-s-92** [comment]
Thanks for answering. But what have I done wrong here? How to solve the issue now?

**Comment by thorsteneb** [comment]
See above. Configure a sepolia checkpoint server. `nano .env` and set `RAPID_SYNC_URL` to a checkpoint server on sepolia
