### ISSUE TITLE
Dashboards disappear after restart

### ISSUE THREAD

**Issue by matthost** [eth-educators/eth-docker#1644]
1. Setup eth-docker, everything is good! Good dashboards are automatically there.
2. Restart the machine to test its behavior
3. On restart, the grafana endpoint is running but the dashboards that were there have disappeared (page shows: _No dashboards yet. Create your first!_)

**Comment by matthost** [comment]
Is there a command I can run to restore them?

**Comment by matthost** [comment]
Reading other issues it mentions dashboards are provisioned on start, I restarted my router at the same time so maybe lack of internet caused the dashboards to fail to retrieve?

**Comment by yorickdowne** [comment]
Really not sure, dashboards should still have been there. Without further info as to what was in the file system at the time, hard to say what happened.
