### ISSUE TITLE
ethd terminated with exit code 128 on line 1008

### ISSUE THREAD

**Issue by ardevd** [eth-educators/eth-docker#1645]
Tried updating from v2.3.8 now and go the following:

```
 ./ethd update
fatal: A branch named 'main' already exists.

./ethd terminated with exit code 128 on line 1008
This happened during ./ethd update
```

Did a manual git pull but the same error is returned. Any ideas?

Line 1008 
` ${__as_owner} git branch -m master main`

I could just check out a tag, do `git branch -d main` and I presume it would solve the issue, but not sure if that's intended behaviour here.

**Comment by yorickdowne** [comment]
Oh interesting. I wonder why that git command failed. It's intended that it change master to main; it's not intended that this git command fails.

I'll try and reproduce that. Thank you!

**Comment by yorickdowne** [comment]
Done. I am puzzled how you ended up on `master`, that branch was renamed to `main` over a year ago.

When in doubt, you may want to `git reset --hard origin/main` once on the `main` branch, to make sure you're in sync ... as long as you don't have local changes that is.
