### ISSUE TITLE
Expose metric port to the host

### ISSUE THREAD

**Issue by salanfe** [eth-educators/eth-docker#1646]
I'm monitoring my EL and CL clients directly with the grafana agent running as a systemd daemon. For me, it makes the setup much simpler: the agent is installed with ansible - fully automated.

However, in order for the monitoring port (let's say teku 8008) to be exposed outside of the docker network, I've edited the file `teku.yml` with the following line

```yaml
    ports:
      - 8008:8008
```

so that the grafana agent can call it.

Even though it's a very simple manual change, it would be much better to pilot everything from the `.env` file.

Maybe it's as simple as extending the files `el-shared.yml` and `cl-shared.yml` with the metrics port. Or maybe there's a better alternative.

What do you think ?

**Comment by yorickdowne** [comment]
I think that's very niche. Feel free to create a yml file for your own setup that does this, and `git commit` the changes. If you have it in a separate yml file, it won't conflict with whatever changes Eth Docker makes.

The two most common ways to use Grafana with Eth Docker are:
- Integrated with `grafana.yml`
- To a remote Grafana/Mimir/Loki stack, either your own or 3rd party, with `grafana-cloud.yml`
