### ISSUE TITLE
ethd keys prepare-address-change not working

### ISSUE THREAD

**Issue by shamoya** [eth-educators/eth-docker#1659]
Hi

First, just wanted to thank you for this great great work.
Been using it for ~ 2 years and it's perfect for my needs.

Trying to run
./ethd keys prepare-address-change
Generating offline prep file
Error: failed to process: failed to obtain validators: GET failed with status 404: {"message":"Not Found","code":404}
Running ethdo failed, unfortunately. Is the CL running and synced?
Please try again after fixing root cause. Aborting. 

Any ideas ?

**Comment by shamoya** [comment]
Yes of course (see below).
It's something to do with the ethdo command, still haven't figured it out.
Running manually from the ethdo docker:

root@996a15595592:/app# gosu ethdo /app/ethdo --connection http://consensus:5052 --allow-insecure-connections node info
Syncing: false


root@996a15595592:/app# gosu ethdo /app/ethdo --connection http://consensus:5052 --allow-insecure-connections validator credentials set --debug
Increasing timeout to 5m0s
Failed to read offline preparation file: stat offline-preparation.json: no such file or directory
Populating chain info from beacon node
Error: failed to process: failed to obtain validators: GET failed with status 404: {"message":"Not Found","code":404}

**Comment by thorsteneb** [comment]
What's the `COMPOSE_FILE` in `.env`? To reproduce this I need to know which clients are in use.

**Comment by shamoya** [comment]
Sorry, thought i pasted it

COMPOSE_FILE=prysm.yml:geth.yml:grafana.yml:grafana-shared.yml:mev-boost.yml:ethdo.yml

**Comment by shamoya** [comment]
@yorickdowne Thanks for the update
