### ISSUE TITLE
create-withdrawal-change.sh falsely assumes that just because the ping fails, that the machine is safely offline.

### ISSUE THREAD

**Issue by lodotek** [eth-educators/eth-docker#1670]
https://github.com/eth-educators/eth-docker/blob/9d6aa2471c98bc4f8663530b17db4b3396e3ae8d/.eth/ethdo/create-withdrawal-change.sh#L34-L35C33

A machine might actually be online but this test will think it's not if the user in which runs this script is a non-root user without permission to ping which results in an error like:
```
ping -v 1.1.1.1
ping: socket: Operation not permitted
```
Which would make the script think that the machine is offline, when in-fact it is online.

**Comment by yorickdowne** [comment]
Hmm. I haven't seen a Live USB where ping is disallowed for the default user. Which one did you use, and do you have a suggestion on how to strengthen this test?

**Comment by yorickdowne** [comment]
Offline detection is now slightly less naive. It still assumes that the user can do ping to be successful, which is true on Ubuntu Live and Tails Live.

wget and curl can't be assumed to be available. Still curious which Live USB actually disallows ping.
