### ISSUE TITLE
feature request: automatically import dashboard json for selected EL client from ./ethd config

### ISSUE THREAD

**Issue by d1onys1us** [eth-educators/eth-docker#1676]
logging a friction i experienced when setting up my eth-docker holesky archive node:
- entered localhost:3000 to visit the dashboard, noticed lighthouse was there but geth was not
- visited eth-docker docs, and found the dashboard page, clicked it, cmd + A and copied it all
- imported the geth prometheus dashboard into grafana

to my knowledge, i believe this used to be automatic. i'm not sure why it's a manual process for me now to import the dashboard.

## feature request

my feature request is if we can have the dashboards of their selected EL client already imported when they visit grafana. this should help create a smoother end user experience!

**Comment by yorickdowne** [comment]
Hmm, that should actually be automatic. I'll take a look for Geth in particular

**Comment by yorickdowne** [comment]
Tested it, "works here". You may want to run a `git status` to make sure you're on the current version of Eth Docker and there aren't local changes stopping an update.

If you continue to  have issues, please come to Ethstaker Discord to troubleshoot.
