### ISSUE TITLE
Add guidance + script for multi-client for validators running majority client

### ISSUE THREAD

**Issue by d1onys1us** [eth-educators/eth-docker#1699]
What do you think of this @yorickdowne? Idea comes from here: https://x.com/arixoneth/status/1744154167407419799

## Feature description

Educate users on running multi-client if they choose to run a majority client (such as Geth), as their risk is 32 ETH on the table if they finalize an invalid fork on their validator.

## Implementation

Some simple script perhaps that polls each eth-docker client (the main validator one and also the "double check" one), and compares. Can query for the latest block hash every 12 seconds and compare, if they mismatch halt the clients with `./ethd down`.

**Comment by yorickdowne** [comment]
I'd rather not. Responded on Xitter and added a risk analysis to the spreadsheet, as I see it.

https://x.com/yorickdowne/status/1744345914381066358?s=20

**Comment by yorickdowne** [comment]
However, https://github.com/TennisBowling/executionbackup does that. It sure beats a mono-culture Geth setup. People who see the risk differently and want to keep Geth could run that.
