### ISSUE TITLE
cadvisor error

### ISSUE THREAD

**Issue by feeleep75** [eth-educators/eth-docker#1726]
I am getting this error with btrfs partition:

`eth-docker-cadvisor-1                   | W0201 08:33:18.608983       1 fs.go:595] Unable to get btrfs mountpoint IDs: stat failed on /dev/md4 with error: no such file or directory`

`eth-docker-cadvisor-1                   | W0201 08:33:18.708159       1 fs.go:595] Unable to get btrfs mountpoint IDs: stat failed on /dev/md4 with error: no such file or directory`

**Comment by yorickdowne** [comment]
Fun. Suggestions on how to handle that? I don't have a btrfs to test

**Comment by yorickdowne** [comment]
All I can find is https://github.com/google/cadvisor/issues/3357 . Short of a fix for cadvisor, there's not much I can do.
