### ISSUE TITLE
got error on run any of ./ethd command

### ISSUE THREAD

**Issue by misha200119** [eth-educators/eth-docker#1728]
got this error message
[./ethd: line 3298: syntax error near unexpected token `&']

**Comment by yorickdowne** [comment]
First, check whether your installation is up to date. `git status` to verify nothing blocks updates then `git pull`

Second, if this is macOS, be sure to follow prerequisites in the docs and install bash 5.

If neither of these help, please say which OS and version you are attempting to install this on.

**Comment by yorickdowne** [comment]
Come to ethstaker Discord if this persists, please.
