### ISSUE TITLE
Prometheus Traefik Error msg="Could not define the service name for the router: too many services"

### ISSUE THREAD

**Issue by 0xCVH** [eth-educators/eth-docker#1748]
I have all traefik services enabled in my .env, however when I configured `prometheus-traefik.yml` I started getting these errors:

```
time="2024-02-12T10:07:37-03:00" level=error msg="Could not define the service name for the router: too many services" providerName=docker routerName=prometheus
```

Seems the YAML file was missing to define the service name, which I have added to the YAML file
```
 - traefik.http.routers.${PROM_HOST:-prom}.service=${PROM_HOST:-prom}
```

That got rid of the error message, but I still am getting a Bad Gateway when heading to https://prometheus.mydomain.com

Any ideas?

**Comment by yorickdowne** [comment]
Well spotted, thank you. I made that change.

Re the 502 error, what is traefik showing you when you enable debug logs? You may also want access logs if debug isn't enough.

**Comment by 0xCVH** [comment]
I uncommented the `access_logs` commands in traefik-cf.yml, but nothing

How to see the access logs? Debug isn't showing anything new.

**Comment by 0xCVH** [comment]
Ok, I figured, its trying to access the execution container at port :9090, instead of Prometheus container. Why? Still investigating

**Comment by 0xCVH** [comment]
Ok, issue here, it was using the execution service

```
# To be used in conjunction with grafana.yml
# Please be very cautious, prometheus is not authenticated by default
version: "3.9"
services:
  ~~execution~~ prometheus:
    labels:
      - traefik.enable=true
      - traefik.http.routers.${PROM_HOST:-prom}.service=${PROM_HOST:-prom}
      - traefik.http.routers.${PROM_HOST:-prom}.entrypoints=websecure
      - traefik.http.routers.${PROM_HOST:-prom}.rule=Host(`${PROM_HOST:-prom}.${DOMAIN}`)
      - traefik.http.routers.${PROM_HOST:-prom}.tls.certresolver=letsencrypt
      - traefik.http.services.${PROM_HOST:-prom}.loadbalancer.server.port=9090
```

**Comment by yorickdowne** [comment]
Thanks. This was clearly never actually tested by me :sweat_smile: . Fix will be in shortly
