### ISSUE TITLE
Why has AlertManager been removed?

### ISSUE THREAD

**Issue by 0xCVH** [eth-educators/eth-docker#1753]
https://github.com/eth-educators/eth-docker/pull/1067/commits/657a5d0e2254a9c24de5c90f16984d0e83be5c7b

Why has it been removed?

**Comment by yorickdowne** [comment]
This was removed a long while ago, in favor of Grafana's built-in alert handling. That's easier to configure for users.

You can use `grafana-cloud.yml` and ship your metrics and logs to your own Grafana/Mimir/Loki stack, and handle alerting any way you want. See the `prometheus/custom-prom.yml.sample` for metrics remote write and the `promtail/custom-lokiurl.sample` for sending logs to your own Loki.
