### ISSUE TITLE
Some Lodestar dashboard metrics are broken

### ISSUE THREAD

**Issue by nflaig** [eth-educators/eth-docker#1755]
**Problem**

Noticed some metrics are broken

![image](https://github.com/eth-educators/eth-docker/assets/38436224/63d02ec6-84ce-43bf-9bf4-27c37b92591b)

likely since https://github.com/eth-educators/eth-docker/pull/1621 because it relabels the job label to use docker service name
https://github.com/eth-educators/eth-docker/blob/64a933b00fcc52af37746abf10e425ab78c5eacb/prometheus/base-config.yml#L30-L31

The problem is that dashboard uses job as a selector in some metrics, e.g. `lodestar_version{job=~"$beacon_job|beacon"}` but the job is now called `consensus`

See job name in the ls prom config is still correct (as updated in https://github.com/eth-educators/eth-docker/pull/1140)
https://github.com/eth-educators/eth-docker/blob/64a933b00fcc52af37746abf10e425ab78c5eacb/prometheus/rootless/ls-prom.yml#L1-L2

**Possible Solutions**

Job name has to match `beacon` or maybe a better solution is to just update the label selector when downloading the dashboard

https://github.com/eth-educators/eth-docker/blob/64a933b00fcc52af37746abf10e425ab78c5eacb/grafana/provision.sh#L54-L54

**Comment by yorickdowne** [comment]
An even better solution would be for the dashboard to use metrics and not filter on the job name at all. `lodestar_version` should be returned from CL and VC I assume? 

Another way to skin this may be: If the variable $beacon_job exists then what happens when it is set to `consensus`?

It's still far cleaner to not use `job` in Dashboards, as the `job` could be anything. The only thing you know will be there are the metrics themselves, however the user chose to scrape them.

**Comment by nflaig** [comment]
> Another way to skin this may be: If the variable $beacon_job exists then what happens when it is set to consensus?

> It's still far cleaner to not use job in Dashboards, as the job could be anything. The only thing you know will be there are the metrics themselves, however the user chose to scrape them.

I agree that it is not ideal to rely on job label, I added the variables a while ago (https://github.com/ChainSafe/lodestar/pull/5211) to let a user set a custom value when importing the dashboard which works well but this is not supported during dashboard provisioning (https://github.com/grafana/grafana/issues/10786).

> An even better solution would be for the dashboard to use metrics and not filter on the job name at all. lodestar_version should be returned from CL and VC I assume?

Yes, we use the same metric name `lodestar_version` in vc and bn, would have to check what was the reason for this becasue all other custom metrics on the validator client are prefixed with `vc_`.

But this still does not solve the issue that we will need to differentiate based on some label as prometheus defines a set of [standard process metrics](https://prometheus.io/docs/instrumenting/writing_clientlibs/#process-metrics) which should be prefixed with `process_`. Now, we could prefix those as well but I think the purpose of this is to make these metric work with a whole range of standardized dashboards that wanna collect these data points.

**Comment by yorickdowne** [comment]
I have a solution, but its brittle and will break when the Lodestar dashboard gets updated and the location of these variables in the array changes:
`jq '.templating.list[3].query |= "consensus" | .templating.list[4].query |= "validator"'`

**Comment by nflaig** [comment]
> I have a solution, but its brittle and will break when the Lodestar dashboard gets updated and the location of these variables in the array changes: `jq '.templating.list[3].query |= "consensus" | .templating.list[4].query |= "validator"'`

Thanks for the fix, will keep that in mind
