### ISSUE TITLE
Issue with intermittent node operation due to logging errors

### ISSUE THREAD

**Issue by samui68400** [eth-educators/eth-docker#1762]
I'm experiencing intermittent operation of my node, and upon investigating the issue, I found that the logs are displaying errors intermittently. 

As you can see below, the logs are inconsistent, displaying errors such as "command not found" and references to nonexistent directories. 

This inconsistent logging behavior is making it difficult to diagnose and troubleshoot the underlying issues causing the intermittent operation of the node.

I would appreciate any assistance or insights into resolving this issue. Please let me know if you need any additional information.

```-bash: root@vmi1113250:~/simple-taiko-node#: No such file or directory
01:53:33.314]: command not found
root@vmi1113250:~/simple-taiko-node# INFO: command not found
INFO:: command not found
root@vmi1113250:~/simple-taiko-node# 01:53:33.314]: command not found
01:53:33.314]:: command not found```

**Comment by yorickdowne** [comment]
One, you're running as `root`, which Eth Docker does not support. Two, the logs you are showing don't give enough detail to know what's going on.

Please come to Ethstaker Discord to get some help, this github is not well-suited for interactive troubleshooting.
