### ISSUE TITLE
./etdh stop then ./ethd up not syncing

### ISSUE THREAD

**Issue by userbox020** [eth-educators/eth-docker#1767]
hello,
What files do i need to delete or what command i need to perfomr to start a fresh sync from genesis block?
I have stoped and stared many times the containers wihtout problem but now they dont want to sync anymore so i dont know what to do.

**Comment by yorickdowne** [comment]
Ethd resync-consensus for the consensus client and ethd resync-execution for the execution client

Please use ethstaker discord to seek support

**Comment by userbox020** [comment]
thanks bro @yorickdowne you guys rocks!
