### ISSUE TITLE
Hello, everytime i restart my computer my node brokes

### ISSUE THREAD

**Issue by userbox020** [eth-educators/eth-docker#1771]
Im using reth+prysm but everytime i restart my computer the node brakes and dont want to sync.
The consensus layer says the execution layer is not syncing and the excution layer says its problem from the consensus layer.
So each one blame to the other.
Do im doing something wrong? should i do ./etdh stop before restarting my computer?

**Comment by yorickdowne** [comment]
You do not need to stop manually, Docker will do a graceful shutdown. Please make sure the P2P ports are reachable via https://www.yougetsignal.com/tools/open-ports/ , and if you continue to have issues, come to ethstaker Discord to troubleshoot. Github is for bug reports, not interactive troubleshooting.
