### ISSUE TITLE
Invalid hostPort error when running `update`

### ISSUE THREAD

**Issue by ColinCampbell** [eth-educators/eth-docker#1774]
I'm running `./ethd update` and running into an error with an invalid hostPort
```
ethereum@staker:~/ethstaker$ ./ethd update
From https://github.com/eth-educators/eth-docker
 * branch            main       -> FETCH_HEAD
Already up to date.
Total reclaimed space: 0B
invalid hostPort: 10.10.100.10148654

./ethd terminated with exit code 15 on line 20
This happened during ./ethd update 
```

The relevant parts in my `.env` would seem to be:

```
HOST_IP=10.10.100.101
CL_P2P_PORT=48654
```

I'm wondering if this is related to getting rid of support for docker compose v1?

**Comment by ColinCampbell** [comment]
https://github.com/eth-educators/eth-docker/blob/main/teku-allin1.yml#L50

Changing the ports definition to 
```
    ports:
      - ${HOST_IP:-}:${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/tcp
      - ${HOST_IP:-}:${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/udp
```
fixes the issue. Is this correct? Happy to create a pull request

**Comment by yorickdowne** [comment]
Thanks! I had missed updating the allin1 files.
