### ISSUE TITLE
Conflicting Prometheus with Rocket pool

### ISSUE THREAD

**Issue by xAslan** [eth-educators/eth-docker#1777]
I have installed eth-docker to run the EL and CL clients and am trying to run rocketpool in addition. RP seems to be able to connect to the ethd clients, but both sets of dashboards seem broken. I'm guessing it has something to do with 2 instances of prometheus running, or 2 containers both named prometheus? Looks like ethd uses prometheus on port 9090 and rp on port 9091, so it seems like they should be ok, but something is catching. Just wondering if anyone has come across this and found a way to run the rocketpool and ethd containers together and get grafana/prometheus dashboards for either working.

**Comment by yorickdowne** [comment]
Yes, people have solved this. Recommend asking in the RocketPool or Ethstaker Discords.
