### ISSUE TITLE
[Question] Possibility to set FEE_RECIPIENT per validator ?

### ISSUE THREAD

**Issue by kalistace** [eth-educators/eth-docker#1783]
Hi,

First all, thanks for this project. Helped me a lot with my setup.

It seems currently it's only possible to set the FEE_RECIPIENT once for all validators. 

With upcoming smoothing pool option coming (https://docs.smoothly.money/how-to-guide), I think it would be interesting to offer the possibility to set the FEE_RECIPIENT per validator instead of a global config. 

This would allow users to fine tune which validator is part of a pool and which is not.

If there's a way to do this already, I'd also be interested to hear it.

Thanks

**Comment by yorickdowne** [comment]
`./ethd keys get-recipient`, `./ethd keys set-recipient`, `./ethd keys delete-recipient`
