### ISSUE TITLE
Eth Docker does not know how to install Docker on linuxmint

### ISSUE THREAD

**Issue by MarcusWentz** [eth-educators/eth-docker#1789]
After running:
```shell
cd ~ && git clone https://github.com/eth-educators/eth-docker.git && cd eth-docker
./ethd install
```
I get the following error:
```shell
Eth Docker does not know how to install Docker on linuxmint
```
I remember using eth-docker months ago on Linux Mint with no issues. 
Did something change or am I missing something? 

docker
```shell
docker --version
```

returns
```shell
Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1
```

docker-compose
```shell
docker-compose --version
```
returns
```shell
docker-compose version 1.29.2, build 5becea4c
```

**Comment by MarcusWentz** [comment]
I am running the following commands instead to avoid this install command issue:
```shell
git clone https://github.com/eth-educators/eth-docker
cd eth-docker
./ethd config
```
source:
https://docs.taiko.xyz/guides/run-a-holesky-node/#steps

**Comment by yorickdowne** [comment]
Eth Docker works on Linux Mint but won't install Docker for you - it only knows how to do that on Ubuntu and Debian. Skip the install command, and install docker-ce yourself.
