### ISSUE TITLE
config fail

### ISSUE THREAD

**Issue by thomasyuenxr** [eth-educators/eth-docker#1791]
After running 
```shell
git clone https://github.com/eth-educators/eth-docker

cd eth-docker

./ethd config
``` 

got error
```shell
Will use sudo to access Docker
You chose to run on holesky testnet
Your deployment choice is: rpc
Your consensus client file is: lighthouse-cl-only.yml
Your execution client file is: geth.yml
Your checkpoint sync URL is: https://holesky.beaconstate.info
Your rewards address is: 0xDCcBAe5B2141d6d65b33572A05C963807176f580
Your COMPOSE_FILE is: lighthouse-cl-only.yml:geth.yml:grafana.yml:grafana-shared.yml
Total reclaimed space: 0B
invalid interpolation format for services.execution.build.args.[]: "'$(git describe --tags $(git rev-list --tags --max-count=1))'". You may need to escape any $ with another $

./ethd terminated with exit code 15 on line 20
This happened during ./ethd config
```

**Comment by yorickdowne** [comment]
This sounds like a compose V1. Unfortunately my detection seems to fail, and I'm not sure why. What should happen is that eth docker complains and offers to install compose V2

Please remove compose V1 and install compose V2. Things should then work.

If you continue to have issues, please come to ethstaker Discord

**Comment by lesywix** [comment]
![image](https://github.com/eth-educators/eth-docker/assets/15158000/59a34c57-e4b0-45b1-9c64-d899cc3cd776)
Hi, I also encounter this issue and my docker compose version is v2.50.

**Comment by yorickdowne** [comment]
Same thing. Make triply sure, check with apt whether docker-compose is installed and uninstall if so (should be docker-compose-plugin for docker-ce or docker-compose-v2 for docker.io), and if issues persist come to Discord

**Comment by lesywix** [comment]
After I change the root user to a non-root user, it works fine.

**Comment by yorickdowne** [comment]
Huh, surprising … I check for whether it runs as root and should complain if it does. Glad to hear that fixed it.
