### ISSUE TITLE
ERROR Invalid JWT: provided signature is invalid

### ISSUE THREAD

**Issue by userbox020** [eth-educators/eth-docker#1801]
Hello, I installed a second node on same host and then I start to get the JWT error. I deleted the file, did an etdh update and etdh up but still same error, both showing up on both of my nodes

https://github.com/paradigmxyz/reth/issues/7628

**Comment by yorickdowne** [comment]
You likely have those in the same docker network. Please make sure you have separate directory names (git clone url dirname); eth-docker dir twice won’t work well.

if you intend for these to be on the same docker network make sure you use different EL_NODE. By default network-execution is available, eg mainnet-execution and holesky-execution.

If you just use “execution” and the two stacks are on the same docker network, docker will round robin, and that’s going to cause failures.

Further discussion on ethstaker Discord please

**Comment by userbox020** [comment]
thanks
