### ISSUE TITLE
chown: invalid group

### ISSUE THREAD

**Issue by bearice** [eth-educators/eth-docker#1827]
I ran into this error after updating to the most recent version of eth-docker:

```
chown: invalid group: ‘bearice:bearice’

./ethd terminated with exit code 1 on line 207
This happened during ./ethd up
```

And I think in #1823 there is an incorrect assumption that a user's main group shares the same name, which I don't: `uid=1000(bearice) gid=100(users)`

**Comment by yorickdowne** [comment]
Thanks I’ll take a look
