### ISSUE TITLE
How to use self hosted web3signer instead of docker

### ISSUE THREAD

**Issue by kajeagentspi** [eth-educators/eth-docker#1840]
So what we planning on doing is to run multiple nodes across multiple machines but they need to use our own web3signer instance so they can use the slashing protection feature. I was wondering since there's a EL_NODE, CL_NODE and MEV_NODE there might be something similar for web3signer.

**Comment by yorickdowne** [comment]
Interesting. Would it not make sense to set this up in the "usual way" for larger installations, that is, multiple CL:EL and then web3signer and VCs in k8s? We have published charts for this (not terribly well documented tbh).

**Comment by yorickdowne** [comment]
Our charts are at https://github.com/CryptoManufaktur-io/eth-staking-charts . I'll be closing this, it's a non-trivial amount of work and someone who runs Web3signer in k8s can also run the VC there, then point that to CL:EL in Eth Docker.

EthStaker Discord is the place to discuss the helm charts.

**Comment by victorelec14** [comment]
@yorickdowne can we please reopen this proposal ??, I find it super interesting, I was looking at the code and the websigner is hard programmed (websigner:9001), maybe we can put the URL in the .env ?

In my almost I want to have the Keys in a separate VM to simplify my backups without having to include all the CL and EL in the backup, for the moment I have it like this:

VM1 : WebSigner, CL
VM2: EL

I want to change to 
VM1: WebSigner
VM2: EL + CL

Thanks

https://github.com/eth-educators/eth-docker/blob/167abde391f22b7438465624b8d9ac79a78907a1/nimbus/docker-entrypoint.sh#L104
