### ISSUE TITLE
Seems Sed fix on #1839 might have broken config for Linux

### ISSUE THREAD

**Issue by haroldsphinx** [eth-educators/eth-docker#1841]
Trying to use eth-docker to setup ssv-node on holesky and this is the error I'm getting, from my investigation, there was a recent merge that fixed sed issues for MacOs, and since this has been working for me prior to this release, I'm assuming it has something to do with the recent fix

```
Canceled config wizard.

You chose to run on holesky testnet
Your deployment choice is: ssv
sed: can't read s/  Network: .*/  Network: holesky/: No such file or directory

./ethd terminated with exit code 2 on line 2918
This happened during ./ethd config
```

**Comment by yorickdowne** [comment]
Can't win for losing. Thanks, will take a look!
