### ISSUE TITLE
Add Vouch as validator client option

### ISSUE THREAD

**Issue by nflaig** [eth-educators/eth-docker#1874]
Was just wondering if there are plans to add [Vouch](https://github.com/attestantio/vouch) as validator client option. It's not as common for solo stakers but I think it's still interesting as an option if you run multiple beacon nodes.

**Comment by yorickdowne** [comment]
Vouch behaves very very differently, so I've decided not to shoehorn it in here. vouchdirk-docker is the repo that handles Vouch. It configures for 2 Vouch and 3/5 Dirk and users can then deploy on five instances across five regions, back-ending to N CL:EL which can if desired be run with Eth Docker

For users that want a single signer, web3signer is a better choice IMO. The allure of Vouch is a) multi-client and b) threshold signing. It doesn't support keymanager

If Vero VC starts supporting keymanager, then that would be a good choice for multi-client with web3signer.

**Comment by nflaig** [comment]
Makes sense, didn't know about https://github.com/CryptoManufaktur-io/vouchdirk-docker, but looks like a good solution.
