### ISSUE TITLE
ethd: line 748: dodocker: command not found

### ISSUE THREAD

**Issue by victorelec14** [eth-educators/eth-docker#1927]
Hi, after upgrading I got this error.

> Eth Docker v2.12.2.0

```txt
 => => naming to docker.io/library/prometheus:local                                                                                                                                       0.0s
/home/xxx/eth-docker/ethd: line 748: dodocker: command not found
/home/xxx/eth-docker/ethd: line 748: dodocker: command not found

ethd terminated with exit code 127 on line 748
This happened during ethd update 
```

https://github.com/eth-educators/eth-docker/blob/main/ethd#L748
```shell
# Has db been initialized?
  __db_exists=$(dodocker run --rm -v "$(dodocker volume ls -q -f "name=$(basename "$(realpath .)")[_-]reth-el-data")":"/var/lib/reth" \
      alpine:3 sh -c 'if [ -f "/var/lib/reth/db/database.version" ]; then echo true; else echo false; fi')
  if [ "$__db_exists" = "false" ]; then
    return 0
  fi
```

Use `ethd resync-execution`  and `ethd prune-reth` has no effect. 

Remove the reth.toml config file hast no effect:
> docker compose exec execution rm /var/lib/reth/reth.toml

Remove the reth volume, after that the update can continue but the blockchain must be re-synchronized.  :/
> docker volume rm eth-docker_reth-el-data

this happens on 3 nodes, only 1 can continue after deleting the entire Reth docker volume.

Thanks

**Comment by jimi3** [comment]
Got the same error on this new reth / nimbus node.

**Comment by yorickdowne** [comment]
Thanks for the PR that fixes this, @kajeagentspi !
