### ISSUE TITLE
unattended ssv-node install

### ISSUE THREAD

**Issue by kristjank** [eth-educators/eth-docker#1954]
Is there a way to do an unattended ssv-node install. So the public key is just generated and stored locally and operator ID can be picked up later when operator is registered.... 

could not find it in docs

**Comment by yorickdowne** [comment]
Yes of course. Edit `.env` as desired, edit `ssv-config/config.yaml` as desired, create the password and key as per SSV docs in `ssv-config` and make sure they are owned by `12000:12000` and have `600` or `400` permissions.
