### ISSUE TITLE
How to use eth-docker to run RPC node which is synced to the custom devnet?

### ISSUE THREAD

**Issue by Nomad-Free-Talent** [eth-educators/eth-docker#2013]
Dear eth-docker engineers.
I'm working on a project where eth-docker is used essentially to spin up the RPC nodes.
At this moment, I'm using [ethereum-package](https://github.com/ethpandaops/ethereum-package) to start the devnet system.
For the development purpose, I need to run another RPC node which is synced to the devnet.
I cloned the `network-configs` folder which is used by `ethereum-package` and then update it by adding bootnodes.txt and bootstrap_nodes.txt files which are holding the enode and multiaddress of geth and lighthouse nodes.
Then, I tried to store this folder in github and use eth-docker's "custom network" feature by setting this folder for its network form.
I confirmed that the geth node from eth-docker is properly synced to the devnet's geth node.
However, the lighthouse node is not synced. Here's the screenshot of its log. It's showing some slot numbers which does not matching with the devnet's ones.
![image](https://github.com/user-attachments/assets/c3d5a479-c2bd-4357-a6c9-6a6399a5c8b4)
And from the execution node's log, I can see that it's not synced with the lighthouse.
![image](https://github.com/user-attachments/assets/c1cee119-38fc-4e89-a4f7-ce274b83faf9)
Here's the network-configs folder I tried to use to start the eth-docker.
https://github.com/Nomad-Free-Talent/interstate-devnet/tree/main/network-configs
Can you help me to troubleshoot this issue, please?

**Comment by yorickdowne** [comment]
Merry Christmas. 

Interesting one. This feature was added at the request of Barnabas of ethpandaops, and I don't know how much testing it got.

I notice Lighthouse has 0 peers as well, which means either bootnodes isn't being handed to it correctly, or the bootnodes aren't reachable.

It's an interesting use case. I'll take a look.

**Comment by yorickdowne** [comment]
This appears to be a problem with your bootnodes, not with Eth Docker.

```
consensus-1  | Dec 29 08:59:06.964 ERRO Error getting mapping to ENR            error: Timeout, multiaddr: /ip4/5.78.46.151/tcp/32821/udp/32776/p2p/16Uiu2HAm79LXSiDcYemaxoa9BMfeNQh9GhYMvr8uzQAiBSCYNXq4, service: libp2p
consensus-1  | Dec 29 08:59:06.964 ERRO Error getting mapping to ENR            error: Timeout, multiaddr: /ip4/5.78.46.151/tcp/32824/udp/32777/p2p/16Uiu2HAkvonB91orD4Xd6uv4EwMqnzmGaw4vPwZTS1L9oxnkoETc, service: libp2p
```

Lighthouse starts with

```
--boot-nodes=/ip4/5.78.46.151/tcp/32821/udp/32776/p2p/16Uiu2HAm79LXSiDcYemaxoa9BMfeNQh9GhYMvr8uzQAiBSCYNXq4,/ip4/5.78.46.151/tcp/32824/udp/32777/p2p/16Uiu2HAkvonB91orD4Xd6uv4EwMqnzmGaw4vPwZTS1L9oxnkoETc
```

I'll be closing this issue. If it appears there's an issue in Eth Docker, not in your devnet setup, it can be re-opened.

`ps -axuww | grep lighthouse` is your friend, as are the startup logs.
