### ISSUE TITLE
data-dir for `slashing_protection.json` ?

### ISSUE THREAD

**Issue by 0x1a4f7d58** [eth-educators/eth-docker#473]
I have this set-up [Configuration A: Chain databases in RocketPool](https://eth-docker.net/docs/Support/Rocketpool) and wish to import solo staking keys as per [Import keys into new client](https://eth-docker.net/docs/Support/Moving#import-keys-into-new-client).

However, before doing this, want to import `slashing_protection.json` to protect against slashing. I'm moving from another client.

Where should I import the file to? It's not clear from the docs atm.

**Comment by yorickdowne** [comment]
This is not yet supported. I'll leave this issue open as a tracker to implement that functionality,

**Comment by yorickdowne** [comment]
This has now been implemented. `slashing_protection.json` can be placed in `./.eth/validator_keys/` alongside keystore json files, and will be imported by `./ethd keyimport` if it exists.
