### ISSUE TITLE
Geth completes syncing but consensus client is still using fallback execution client

### ISSUE THREAD

**Issue by 1mdc** [eth-educators/eth-docker#475]
I'm using geth + teku on my local setup.

In teku, I use geth as main eth1 endpoint and infura as a fallback.

After about 30 hours, geth is seem completed now. I see its head is same as the one in etherscan. However, teku is still using fallback infura endpoint rather than geth. I can see the number of request in infura dashboard is quite high. I tried to restart all services, it does not help.

**Comment by yorickdowne** [comment]
This is a question for the Teku team. eth-docker is a lightweight wrapper around the clients and does not change their innate behavior.
