### ISSUE TITLE
Question regarding Erigon as Execution Client

### ISSUE THREAD

**Issue by mondsen** [eth-educators/eth-docker#481]
Hi,
thanks for this project. I would like to setup my upcoming node for Staking based on this docker images and will move from Infura to my own Execution Client. I picked Erigon for this.

In your docu, the following is stated:

> Erigon is configured to fully prune itself. This does work with a consensus client, but requires that the consensus client get initial deposit data from another source, such as Infura. There are two ways to make this happen. Either set an Infura failover client and sync the consensus client and Erigon at the same time. Because Erigon will take longer to sync, the Infura failover will be used. Or, alternatively, if the consensus client needs to be re-synced while Erigon is already synced, you can set EC_NODE to be Infura, sync the consensus client, then configure it for Erigon with an Infura failover.

I honestly do not fully understand because I have checked the changelog an see this PR https://github.com/eth-educators/eth-docker/pull/297 with the code 
````
if [[ "$@" =~ "--chain mainnet" ]]; then
  echo "mainnet: Running with prune.r.before=11184524 for eth deposit contract"
  exec "$@" --prune.r.before=11184524
````
which in my eyes would only prune information before PoS Start (December 2020). 

Obviously I would like to use a pruned erigon node but I don't want to rely anymore in Infura. Maybe you can shed some more light in the right direction. :)
Thanks!

**Comment by yorickdowne** [comment]
Ah yes, the docs are out of sync with reality! Fixed.

Thanks for the report!
