### ISSUE TITLE
kiln support

### ISSUE THREAD

**Issue by jakrypto** [eth-educators/eth-docker#486]
Hi I would love to test the kiln merge with eth-docker. From what I understand I need to change the docker images according to https://notes.ethereum.org/@launchpad/kiln - but I think I'm struggeling with bootnodes/keys etc. Any hints?

**Comment by yorickdowne** [comment]
This will be supported by the merge branch, like Kintsugi was. Please bear with me - I am knee deep in other work. I aim to have this going by next week.

**Comment by yorickdowne** [comment]
Kiln support is in with `merge` branch. There's something funky going on with Besu auth that I haven't figured out, ditto Nethermind. Other than that it "just" needs a lot of testing.
