### ISSUE TITLE
How to to debug the SSV network issue?

### ISSUE THREAD

**Issue by lemontreeran** [eth-educators/eth-docker#531]
We hit some network issue as one of SSV validators can't connect with any peers. And how to debug with the flag "[NetworkDiscoveryTrace](https://github.com/bloxapp/ssv/blob/main/network/p2p/config.go#L28)".  
Would you please help and point out how we can turn on this debug option? Thanks so much 🙏

**Comment by yorickdowne** [comment]
All options are in the ssv config yaml file. Recommend asking troubleshooting questions in the SSV discord.
