### ISSUE TITLE
Set restart policy in configuration script

### ISSUE THREAD

**Issue by synthic** [eth-educators/eth-docker#551]
Since the recommended configuration method is through the `ethd` script, would it be possible to add a prompt for setting all deployed containers to have a restart policy of "unless-stopped" for automatic startup?

**Comment by synthic** [comment]
I noticed that default.env is already set this way, but if that is the default maybe it would still be nice to present the option to the user.

**Comment by yorickdowne** [comment]
I am choosing to leave the advanced configuration options out of `./ethd config`. Restart policy, if not desired to be the default, can be changed by the user in `.env`, and will survive an `./ethd update`. Same for ports and such.
