### ISSUE TITLE
Remote consensus client misconfiguration when validator client only

### ISSUE THREAD

**Issue by gwenvador** [eth-educators/eth-docker#571]
When using ./ethd config with a new config (rocketpool integration) the concensus client address in .env is set to http://concensus:5052. It should be http://eth2:5052

**Comment by yorickdowne** [comment]
Hey thanks for the report! I'll take a look and fix that.

**Comment by yorickdowne** [comment]
Yep I broke that pretty bad when changing to EL/CL NewSpeak from EC/CC. Should be working now.
