### ISSUE TITLE
Add besu and teku peer limits

### ISSUE THREAD

**Issue by hoangong** [eth-educators/eth-docker#629]
The default peer limits in these clients are a bit high to handle in average home network.

It is good to have options in .env to limit them. 

* Besu [--max-peers](https://besu.hyperledger.org/en/stable/Reference/CLI/CLI-Syntax/#max-peers)
* Teku had `--p2p-peer-upper-bound=<INTEGER>` but if it is below the minimum `--p2p-peer-lower-bound=<INTEGER>` the upper bound does not work. so it is good to have both lower and upper bound options in .env

Thanks.

**Comment by yorickdowne** [comment]
Hmm good suggestion. I'll add that.
