### ISSUE TITLE
TTD override

### ISSUE THREAD

**Issue by thomkeh** [eth-educators/eth-docker#643]
It would be nice if it was possible to overwrite TTD via the `.env` file. It's not really urgent, but something to keep in mind.

Conveniently, this blog post has all the flag names for all the clients: https://blog.ethereum.org/2022/06/03/ropsten-merge-ttd/#terminal-total-difficulty-override

**Comment by yorickdowne** [comment]
It is possible to override TTD via the `.env` file. Please use the `merge-getready` branch for all merge testing.
