### ISSUE TITLE
OVERRIDE_TTD is being set incorrectly for Ropsten merge

### ISSUE THREAD

**Issue by dcbuild3r** [eth-educators/eth-docker#654]
This issue refers to the `merge-getready` branch. 

I've been running eth-docker for the Ropsten merge with a client combination of Lighthouse + Geth and I noticed that the TTD of  my clients pointed to 100000000000000000000000 instead of 50000000000000000. I presume that some part of the script made it default to the last line of the `query_override()` if else statement. I've already wiped my ropsten validator, but this is what prevented my clients from finalizing the first merge block as they expected it to happen much later and I couldn't change the TTD to 50000000000000000 however I tried. Would appreciate any input so that the same doesn't happen to me when running a node for Goerli and Sepolia. I'm a newbie in terms of running clients, so please bear with me :).

https://github.com/eth-educators/eth-docker/blob/eea7e13531fc48daaa9e34f5996411bde478d9d5/ethd#L766-L777

**Comment by yorickdowne** [comment]
This is just the config script. The override TTD is set in `.env` and can be changed manually as desired. An `./ethd update` should have brought in the right TTD. If you have local changes that are not committed, this can cause issues.

**Comment by dcbuild3r** [comment]
Thank you for answering my doubts, this indeed solved my issues. I didn’t find this step in `MERGE-READY.md`, it’d be a nice addition to the guide, especially for newbies like me that lack context. Should I submit a PR?

**Comment by yorickdowne** [comment]
Can you tell me which step was missing? By all means, a documentation PR is welcome.

**Comment by dcbuild3r** [comment]
./ethd update for pulling in the new updated TTD after the EF set a new one or that the OVERRIDE_TTD can be found in the .env file. I presume that the other long-standing testnets will not have the same issue with the OVERRIDE so that it is a useless PR moving forward.
