### ISSUE TITLE
Prater SSZ download - Goerli

### ISSUE THREAD

**Issue by aliask** [eth-educators/eth-docker#660]
While testing on Goerli/Prater I ran into an issue with Prysm.
In the entrypoint, the genesis SSZ file does not download correctly, and the beacon-chain client cannot start.

The main issue is that `curl` is called without the `-L` flag, and it receives a `302` response. It saves the empty response to the file instead of following the redirect.
Another small issue is that the empty file also prevents re-download, so the volume must be deleted to recover from a broken SSZ file.

**Comment by yorickdowne** [comment]
Thanks! Shall fix that.

**Comment by yorickdowne** [comment]
Looks resolved in testing.
