### ISSUE TITLE
_eth_1 exited with code 0

### ISSUE THREAD

**Issue by ibootstrapper** [eth-educators/eth-docker#720]
after an update using the command `sudo ./ethd update --keep-targets    `

Logs from `sudo ./ethd logs | grep eth_1`  shows the following:
```
Attaching to eth-docker_eth_1, eth-docker_validator_1, eth-docker_consensus_1
eth-docker_eth_1 exited with code 0
```

Logs from `sudo ./ethd logs` shows the following:

```
consensus_1          | Jul 02 05:08:20.441 CRIT Could not connect to a suitable eth1 node. Please ensure that you have an eth1 http server running locally on http://localhost:8545 or specify one or more (remote) endpoints using `--eth1-endpoints <COMMA-SEPARATED-SERVER-ADDRESSES>`. Also ensure that `eth` and `net` apis are enabled on the eth1 http server, warning: BLOCK PROPOSALS WILL FAIL WITHOUT VALID, SYNCED ETH1 CONNECTION, service: eth1_rpc
consensus_1          | Jul 02 05:08:20.441 ERRO Failed to update eth1 cache             error: Failed to update Eth1 service: "All fallback errored: http://execution:8545/ => EndpointError(RequestFailed(\"Request failed: reqwest::Error { kind: Request, url: Url { scheme: \\\"http\\\", cannot_be_a_base: false, username: \\\"\\\", password: None, host: Some(Domain(\\\"execution\\\")), port: Some(8545), path: \\\"/\\\", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError(\\\"tcp connect error\\\", Os { code: 111, kind: ConnectionRefused, message: \\\"Connection refused\\\" })) }\"))", retry_millis: 60000, service: eth1_rpc
```

**Comment by yorickdowne** [comment]
This looks like you are not running an EL or it's not synced. `eth_1` is not the EL, it's a helper container that will be removed with the next major version.

Verify that you have the yml for an EL in `COMPOSE_FILE` inside `./env`. Logs for it show should with `./ethd logs -f --tail 50 execution`, exception Erigon (for now), where it is `./ethd logs -f --tail 50 erigon`

This will be easier to troubleshoot interactively in ethstaker Discord.

**Comment by ibootstrapper** [comment]
thanks, the eth_1 is exit with code 0 as soon as it starts.

What is ethstaker discord? i'll join and take it from there. Thank you!!!

**Comment by ibootstrapper** [comment]
Just FYI, i disabled eth_1 and changed EL_NODE to point to infura for now
