### ISSUE TITLE
Cannot pull validator-input or deposit-cli

### ISSUE THREAD

**Issue by joeytwiddle** [eth-educators/eth-docker#755]
Following the instructions from [MERGE-READY.md](https://github.com/eth-educators/eth-docker/blob/merge-getready/MERGE-READY.md) but I get an error:

```
[root@server merge-ready]# ./ethd keyimport
[+] Running 0/1
 ⠿ validator-import Error
Error response from daemon: pull access denied for teku, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

Oh, earlier in the process I also had this error:

```
[root@server merge-ready]# docker-compose run --rm deposit-cli-new --eth1_withdrawal_address 0x64b6E8BdF6Bf0296BBD8f332749B2147150F2aaF 
[+] Running 4/0
 ⠿ Network merge-ready_default          Created
 ⠿ Volume "merge-ready_teku-data"       Created
 ⠿ Volume "merge-ready_jwtsecret"       Created
 ⠿ Volume "merge-ready_besu-eth1-data"  Created
[+] Running 0/1
 ⠿ deposit-cli-new Error
```

By the way, it would be good if the docs would show when to run with `sudo`. Because `ethd config` wants to run as a user, but `docker-compose` wants to run as root.

**Comment by yorickdowne** [comment]
Do a `docker-compose build --pull` first. This is done for you with `./ethd config` and `./ethd update`, but if you run more manual, it's up to you.

Docs point out that all docker commands need `sudo` unless your user is part of the `docker` group. That can use another pass for sure. If there's a specific point in the docs where it's unclear, could you point it out, please?

**Comment by joeytwiddle** [comment]
I think the problem was that I started with `MERGE-READY.md` and not with the docs!

**Comment by yorickdowne** [comment]
The ethstaker discord is the best place to engage in support discussions, btw.

If you are running an RPC node, you do not need anything validator-related. This lives in `rpc-nodes` for now, but should come back into `main` maybe in an `adv` directory, at some point.

Mainnet is supported in the `main` branch. The `merge-getready` branch will be merged into `main` once an engine API is available on `main`. Today's ACD should prove instructive for that.
