### ISSUE TITLE
Confused about main and merge-getready branches

### ISSUE THREAD

**Issue by joeytwiddle** [eth-educators/eth-docker#778]
1. Please document on the README what is the difference between `main` and `merge-ready` branches, so users know which one to choose.

2. Furthermore, if `merge-getready` is the recommended branch for current use and development, then you might like to make it the default branch here:

   https://github.com/eth-educators/eth-docker/settings/branches

   That would make it the default for pull requests. And it would also show the files from that branch when someone navigates to the project home on github.

Thanks!

**Comment by joeytwiddle** [comment]
Ah, you answered it here:

https://github.com/eth-educators/eth-docker/issues/755#issuecomment-1191249209

Let me have a play with `main`. Perhaps I will add the documentation myself!

**Comment by yorickdowne** [comment]
Yep as you've found, `merge-getready` is a testing branch to get, well, merge-ready. Once it's safe to deploy a merge-ready setup on mainnet ... not quite yet but Soon(tm) ... it'll be merged into `main`.
