### ISSUE TITLE
Cannot reconfigure `EL_RPC_PORT`

### ISSUE THREAD

**Issue by joeytwiddle** [eth-educators/eth-docker#791]
Using geth and prysm here.

Steps to reproduce:

1. Edit `.env` and change value of `PRYSM_PORT`
2. Run `./ethd restart`
3. See from `docker ps` that the new value has been applied. :heavy_check_mark:
4. Edit `.env` and change value of `EL_RPC_PORT`
5. Run `./ethd restart`
6. See from `docker ps` that the new value has **NOT** been applied! :x:

Expected:

- I was hoping to see `docker ps` forwarding the ports with the new value, e.g. `0.0.0.0:9545-9546->9545-9546/tcp`

Thoughts:

- **I suspect this is the issue:** `EL_RPC_PORT` and `EL_WS_PORT` are applied in `el-shared.yml` but I can't see where that file is actually loaded!

- `docker ps` does show `8545-8546/tcp` so that is being configured somewhere. I guess this comes with the geth docker image.

Workaround:

- Copying the two `ports` lines from `el-shared.yml` into `geth.yml` makes it work for now.

**Comment by yorickdowne** [comment]
You did not have to copy anything here. I recommend undoing the change you made and adding `:el-shared.yml` to your `COMPOSE_FILE` in `.env`

`docker ps` shows ports that the client team's image "exposes". This is an old concept and not terribly useful. So while docker ps shows 8545, that doesn't mean the port is actually in use.

`EL_RPC_PORT` changes the port the EL client listens on for RPC queries.

`el-shared.yml` then maps this port to host. At that point it is reachable, and if the machine is say a VPS, this port should now be firewalled.
