### ISSUE TITLE
updating and migrate to pre-merge

### ISSUE THREAD

**Issue by ibootstrapper** [eth-educators/eth-docker#826]
after update and move to pre-merge i get the following error:

```
ERRO Execution client config mismatch        local: TransitionConfigurationV1 { terminal_total_difficulty: 115792089237316195423570985008687907853269984665640564039457584007913129638912, terminal_block_hash: 0x0000000000000000000000000000000000000000000000000000000000000000, terminal_block_number: 0 }, remote: TransitionConfigurationV1 { terminal_total_difficulty: 115792089237316195423570985008687907853269984665640564039457584007913129638911, terminal_block_hash: 0x0000000000000000000000000000000000000000000000000000000000000000, terminal_block_number: 0 }, msg: ensure lighthouse and the execution client are up-to-date and configured consistently, service: exec
```

when i tried to setup the `JWT_SECRET` at `.env`, follow with a `./ethd update` i get the following error:

```Attaching to eth-docker_consensus_1
consensus_1           | /usr/local/bin/docker-entrypoint.sh: line 5: /var/lib/lighthouse/beacon/ee-secret/jwtsecret: Permission denied
consensus_1           | /usr/local/bin/docker-entrypoint.sh: line 5: /var/lib/lighthouse/beacon/ee-secret/jwtsecret: Permission denied
consensus_1           | /usr/local/bin/docker-entrypoint.sh: line 5: /var/lib/lighthouse/beacon/ee-secret/jwtsecret: Permission denied
consensus_1           | /usr/local/bin/docker-entrypoint.sh: line 5: /var/lib/lighthouse/beacon/ee-secret/jwtsecret: Permission denied
consensus_1           | /usr/local/bin/docker-entrypoint.sh: line 5: /var/lib/lighthouse/beacon/ee-secret/jwtsecret: Permission denied
consensus_1           | /usr/local/bin/docker-entrypoint.sh: line 5: /var/lib/lighthouse/beacon/ee-secret/jwtsecret: Permission denied
consensus_1           | /usr/local/bin/docker-entrypoint.sh: line 5: /var/lib/lighthouse/beacon/ee-secret/jwtsecret: Permission denied
consensus_1           | /usr/local/bin/docker-entrypoint.sh: line 5: /var/lib/lighthouse/beacon/ee-secret/jwtsecret: Permission denied```

**Comment by ibootstrapper** [comment]
by the way...i'm testing it fresh...without a validator configured

**Comment by ibootstrapper** [comment]
some more information...

on the `execution` i get the following:

`
execution_1           | signing key too short, 256 bits required
```

i've try to setup the key as plain string or hex - both 256bit generated , tried several times with different codes generated by different sites as well.

**Comment by yorickdowne** [comment]
Thanks, `JWT_SECRET` has not been tested well yet. I'll take a look. It's meant only for distributed setups, you should leave it empty otherwise.

The execution client mismatch is a known issue on mainnet. There is a standard for the CL side but not for the EL side, hence the mismatch. You will likely see this until a TTD has been announced for mainnet.

**Comment by yorickdowne** [comment]
Tested it ... this happens when you specific a secret but are not running a distributed setup. That is not a use case I considered, but one I may want to allow. Let me see what I can do.

**Comment by yorickdowne** [comment]
I've pushed a change with more robust handling of permissions for jwtsecret in various cases, including this one. Please `./ethd update` and test. If you still have issues, please re-open this issue.

Thank you for the report!

**Comment by ibootstrapper** [comment]
Thanks! Will check as I get home later today.

Let me know if there are any tests you want me to do. I'm with a fresh testing mode for main net

**Comment by yorickdowne** [comment]
Basics really ... does it run, can you import a validator key - obviously not one you deposited for, just a random throwaway one for testing.

**Comment by ibootstrapper** [comment]
Just checked.

the permission issue is resolved. Thank you!

I get the following errors on the consensus :

```
consensus_1           | Aug 06 02:27:09.344 ERRO Error during execution engine upcheck   error: Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("execution")), port: Some(8551), path: "/", query: None, fragment: None }, source: TimedOut }), service: exec
consensus_1           | Aug 06 02:27:09.829 ERRO Execution engine call failed            error: Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("execution")), port: Some(8551), path: "/", query: None, fragment: None }, source: TimedOut }), service: exec
consensus_1           | Aug 06 02:27:09.829 ERRO Unable to get transition config         error: Api { error: Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("execution")), port: Some(8551), path: "/", query: None, fragment: None }, source: TimedOut }) }, service: exec
consensus_1           | Aug 06 02:27:09.829 ERRO Failed to check transition config       error: EngineError(Api { error: Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("execution")), port: Some(8551), path: "/", query: None, fragment: None }, source: TimedOut }) }), service: exec
```

I am running without a validator key imported...as this is on mainnet and the validator is running on my other setup.

**Comment by yorickdowne** [comment]
That means the execution client isn’t running. Check its logs to see what has it in a tizzy

**Comment by ibootstrapper** [comment]
Yes, didn't realize the execution didn't fuly sync. 

Where can I follow on execution client mismatch on mainnet? any github/reditt/discord?

**Comment by yorickdowne** [comment]
The TTD mismatch might not get fixed for mainnet. It's cosmetic. We should see client releases with an actual TTD for mainnet week of the 22nd. The ethstaker Discord is a good place to keep track of what's happening around merge.

**Comment by ibootstrapper** [comment]
Thanks, i'm on the ethstaker Discord. Any specific channel you recommend?
