### ISSUE TITLE
MEV-Boost Support for Lighthouse

### ISSUE THREAD

**Issue by codesport** [eth-educators/eth-docker#846]
Hey Guys,

Can anyone confirm if [mev-boost](https://ethresear.ch/t/mev-boost-merge-ready-flashbots-architecture/11177) support is working for the lighthouse consenus client?

If not which client is it working for?

**Comment by yorickdowne** [comment]
It's working for all clients. Nimbus requires a source build from `unstable`, likely until their next release.

Keep in mind Goerli has not merged, so mev-boost will error on that network until after merge.

**Comment by codesport** [comment]
Yorick,

Thanks for confirming. 

You guys have done an excellent job and have covered all the basis! 👍 

Found this gem from Remy while reviewing July's call: https://youtu.be/DMynQb6MSfc?t=1157
