### ISSUE TITLE
Error "Cannot autolaunch D-Bus with X11 $DISPLAY"

### ISSUE THREAD

**Issue by zgrannan** [eth-educators/eth-docker#884]
After updating to the latest version (and updating docker-compose to 2.6.1), I encountered the following error during `./ethd restart`:

```
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = error getting credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY`
```

I think this has something to do with secret management. Running `sudo apt-get install pass` fixes this problem. I'm not sure if `pass` is ever used actually; as I never setup a PGP key.

**Comment by yorickdowne** [comment]
Curious. Which OS is this?

**Comment by zgrannan** [comment]
I encountered this issue on Debian 10

**Comment by yorickdowne** [comment]
Googling a little. Is docker configured to log you into docker hub? This suggests it may be related to that: https://anto.online/guides/cannot-autolaunch-d-bus-without-x11-display/

**Comment by yorickdowne** [comment]
Closing this for now. If you think there's something to be done here by eth-docker, please re-open
