### ISSUE TITLE
merge-ready branch missing sample-systemd

### ISSUE THREAD

**Issue by davidkassa** [eth-educators/eth-docker#889]
It appears the merge-ready branch is missing the sample-systemd file.

This impacts the Autostart documentation here: https://eth-docker.net/docs/Usage/Autostart

**Comment by davidkassa** [comment]
Also, when I try docker-compose up I get an error that there is no such service: eth. Is there a new way to manage this using ./ethd?

**Comment by yorickdowne** [comment]
Yep systemd is gone, it was superfluous. Docs will be updated when this gets into `main` branch.

`eth` is no longer a thing. Just `docker-compose up -d` does the trick, or `./ethd up`
