### ISSUE TITLE
sample-systemd is missing but mentioned in the docs

### ISSUE THREAD

**Issue by ColinCampbell** [eth-educators/eth-docker#918]
Just wanted to mention that sample-systemd which is mentioned in the [Step 8: Create a service to autostart the node](https://eth-docker.net/docs/Usage/Autostart) docs is missing from the repository since [this commit](https://github.com/eth-educators/eth-docker/commit/b113bbe1fcf90f82b23e2dd4cce6ce714cf880f1). Not sure if the removal of `sample-systemd` was intentional but if it was the docs should likely be updated?

**Comment by yorickdowne** [comment]
I'll make sure to update docs, thank you.
