### ISSUE TITLE
can't import validator key Lodestar

### ISSUE THREAD

**Issue by jojosqsq** [eth-educators/eth-docker#921]
can't import validator key

it say error.

i am use GETH + Lodestar

please see picture. How i can fix that.
![eth-test](https://user-images.githubusercontent.com/111879144/186160012-c6f90b04-665b-4e53-a45c-ecfdde8db0ef.jpg)

**Comment by yorickdowne** [comment]
Please run an `./ethd update` to get an eth-docker that works with current Lodestar. If that has issues during `git pull` because of local changes, resolve those issue, for example by committing or undoing local changes.

**Comment by yorickdowne** [comment]
Please run `./ethd update` and try again.

BTW `./ethd keys` has advantages, such as being able to set individual fee recipients in future, once Lodestar implements that. It's worth a look.

**Comment by jojosqsq** [comment]
good job.

it all ok

![good](https://user-images.githubusercontent.com/111879144/186170144-34cec22c-072e-4860-9f3a-fbb7ec7b725b.jpg)


Thank you
