### ISSUE TITLE
Lodestar "validator" error "getProposerDuties"

### ISSUE THREAD

**Issue by jojosqsq** [eth-educators/eth-docker#933]
Hello
How to fix.
Lodestar "validator" error "getProposerDuties"

![validator](https://user-images.githubusercontent.com/111879144/186576997-1347f202-6cfc-400c-a7bc-5fb92f24e766.jpg)

Thank you

**Comment by yorickdowne** [comment]
Node is syncing. It needs to be done with that. Rapid sync can get you going in minutes, but only from a blank database. Feel free to join ethstaker Discord for further discussion.
