### ISSUE TITLE
Add --validators-keystore-locking-enabled=false to Teku?

### ISSUE THREAD

**Issue by Tristannn1337** [eth-educators/eth-docker#944]
After experiencing a hard reset on my server, I found Teku stopped validating due to the .lock files remaining. I don't believe this behavior is consistent with other clients? So, in the interest of consistent behavior and automatic recovery, I'm wondering if --validators-keystore-locking-enabled=false should be added to teku-base.yml?

**Comment by yorickdowne** [comment]
Good question. Let me ping the Teku team on it.

**Comment by yorickdowne** [comment]
Done.
