### ISSUE TITLE
Geth suddenly unable to connect to peers and can't sync

### ISSUE THREAD

**Issue by ardevd** [eth-educators/eth-docker#964]
Checked my Geth container logs today and found that it's stuck on a block and can't connect to peers. Any suggestions as to what might be wrong and how to fix it?

Here's the log output: https://gist.github.com/ardevd/6c2906db9606e51bba6ec38a10eae790

Any help would be much appreciated.

**Comment by yorickdowne** [comment]
That's not an eth-docker issue. Please try ethstaker Discord or Geth discord.
