### ISSUE TITLE
use prysm got error 

### ISSUE THREAD

**Issue by huayun321** [eth-educators/eth-docker#970]
curl -fsSL -o "$GENESIS" https://github.com/eth-clients/merge-testnets/raw/main/sepolia/genesis.ssz
https://github.com/eth-educators/eth-docker/blob/main/prysm/docker-entrypoint.sh

"curl: (23) Failure writing output to destination"

**Comment by yorickdowne** [comment]
I am unable to reproduce this. I responded in ethstaker Discord
