### ISSUE TITLE
Problem importing wallet public key on mainnet

### ISSUE THREAD

**Issue by TestingValidator** [eth-educators/eth-docker#972]
Good evening,
Following the guide on: (https://eth-docker.net/docs/About/Overview/
After starting the client automatic configuration: Eth-docker Quickstart shell, with the command: "./ethd config", using prysm+geth on mainnet, it won't be possible to import the hardware wallet keys with this command:
"docker-compose run --rm deposit-cli-new --eth1_withdrawal_address YOURHARDWAREWALLETADDRESS --uid $(id -u)"

result will be ERROR: no existing service deposit-cli-new
(or similar...)

OS Ubuntu 22.04 desktop 64 bit.

The problem is not present if the automatic configuration "./ethd config" is done with the Goerli test net.

Thank you,

**Comment by yorickdowne** [comment]
This doesn't import wallet keys, it creates them. You'd need to add `deposit-cli.yml` to `COMPOSE_FILE` if you want to create keys. It's not present by default as the recommendation is to create keys on an airgapped machine.

Key import is handled with `./ethd keys import`, keys are expected in keystore json format in `.eth/validator_keys`
