### ISSUE TITLE
put volume location in .env file

### ISSUE THREAD

**Issue by kornface13** [eth-educators/eth-docker#979]
I think some number of folks probably run secondary hard drives to store chain info.  It would be super handy to have a `base file location` or something in .env.  This would allow me to specify that all containers use `/mnt/2tb/` instead of the default `/var/lib/docker/volumes/` as the location to store their volume.  Without this I have to go in and make changes to the volumes in all of the .yml files that I use, which makes my branch out of sync.  Seems like a simple and great feature to add.

**Comment by yorickdowne** [comment]
The easiest way to do this is to change the docker root volume: https://eth-docker.net/docs/Usage/Prerequisites#change-docker-storage-location

Bind mounts get messy with permissions, that's why I am sticking with docker volumes.
